/* Analyser - proprietary format catalog (data only).
   The FORMATS table that proprietary.js / renderProprietary() drives: maps a
   lowercase extension to { app, parse?, zip?, chunk? }. Split out
   of proprietary.js so the 1000+ line catalog does not bury the parsing logic.
   Pure data, no dependencies.
   ----------------------------------------------------------------------------
   AN ENTRY HAS EXACTLY FOUR KEYS. There is no `icon`, no `magic`.

     app     required. The display name, shown as the card title and the
             "Application" row. A parser may override it at runtime by returning
             `_app` when the bytes prove something more specific (a .cdp is
             either Criterium DecisionPlus or CDP4/COMET - we name whichever the
             bytes show, not both).
     parse   a hint for the generic reader: 'text' | 'xml' | 'html'.
     zip     the file is physically a ZIP, so offer the archive browser.
     chunk   which lazy parser chunk holds its parser. One of:
               gaming docs dev sci audio threed disk image
               archive security video geodata email osmisc raw
             The chunk is fetched only when a file of that domain is opened, so
             the boot bundle stays flat as the catalog grows. `chunk` names WHERE
             the parser lives; the parser itself is registered in that file's
             PARSERS map, keyed by the same extension.

   An entry with `app` alone is identification-only: it names the file and stops.
   That is a complete, legitimate entry - most of this table is exactly that.

   Adding a format here does NOT list it on the site. The catalog/display side is
   core/formats.ts, and the two are deliberately separate: this is parsing wiring,
   that is what users see. A format needs a row in both.
   ---------------------------------------------------------------------------- */

export const FORMATS = {
  // Adobe
  psd:     { app: 'Adobe Photoshop' },
  psb:     { app: 'Adobe Photoshop (Large)' },
  ai:      { app: 'Adobe Illustrator' },
  indd:    { app: 'Adobe InDesign' },
  indt:    { app: 'Adobe InDesign Template' },
  idml:    { app: 'Adobe InDesign (IDML)' },
  aep:     { app: 'Adobe After Effects' },
  aet:     { app: 'Adobe After Effects Template' },
  prproj:  { app: 'Adobe Premiere Pro' },
  prel:    { app: 'Adobe Premiere Elements' },
  mogrt:   { app: 'Adobe Motion Graphics Template' },
  sesx:    { app: 'Adobe Audition' },
  xd:      { app: 'Adobe XD' },
  fla:     { app: 'Adobe Animate / Flash' },
  swf:     { app: 'Adobe Flash (SWF)' },
  afl:     { app: 'Adobe Flash' },

  // Adobe sidecar / settings
  xmp:     { app: 'XMP Sidecar (Adobe metadata)', parse: 'xml' },
  lrtemplate: { app: 'Adobe Lightroom Template' },
  lrcat:   { app: 'Adobe Lightroom Catalog' },
  acv:     { app: 'Adobe Photoshop Curves' },
  aco:     { app: 'Adobe Photoshop Color Swatches' },
  asl:     { app: 'Adobe Photoshop Styles' },
  abr:     { app: 'Adobe Photoshop Brushes' },
  grd:     { app: 'Adobe Photoshop Gradients' },
  pat:     { app: 'Adobe Photoshop Patterns' },

  // CAD - SolidWorks
  sldprt:  { app: 'SolidWorks Part' },
  sldasm:  { app: 'SolidWorks Assembly' },
  slddrw:  { app: 'SolidWorks Drawing' },
  sldreg:  { app: 'SolidWorks Settings', parse: 'text', chunk: 'security' },
  svap:    { app: 'SolidWorks Visualize Appearance', zip: true },
  svpj:    { app: 'SolidWorks Visualize Project', zip: true },

  // CAD - Fusion 360
  f3d:     { app: 'Autodesk Fusion 360' },
  f3z:     { app: 'Autodesk Fusion 360 Archive' },

  // CAD - AutoCAD
  dwg:     { app: 'AutoCAD Drawing' },
  dxf:     { app: 'AutoCAD DXF Exchange' },
  dwt:     { app: 'AutoCAD Template' },

  // CAD - Inventor
  ipt:     { app: 'Autodesk Inventor Part' },
  iam:     { app: 'Autodesk Inventor Assembly' },
  idw:     { app: 'Autodesk Inventor Drawing' },

  // CAD - Other
  '3dm':   { app: 'Rhinoceros 3D' },
  gh:      { app: 'Grasshopper (Rhino)' },
  ghx:     { app: 'Grasshopper XML (Rhino)' },
  skp:     { app: 'SketchUp' },
  '3ds':   { app: 'Autodesk 3ds Max' },
  max:     { app: 'Autodesk 3ds Max Scene' },
  ma:      { app: 'Autodesk Maya ASCII' },
  mb:      { app: 'Autodesk Maya Binary' },
  c4d:     { app: 'Maxon Cinema 4D' },
  hip:     { app: 'SideFX Houdini' },
  hipnc:   { app: 'SideFX Houdini Non-Commercial' },
  zpr:     { app: 'Pixologic ZBrush' },
  ztl:     { app: 'Pixologic ZBrush Tool' },

  // CAD exchange
  step:    { app: 'STEP CAD Exchange' },
  stp:     { app: 'STEP CAD Exchange' },
  iges:    { app: 'IGES CAD Exchange' },
  igs:     { app: 'IGES CAD Exchange' },
  sat:     { app: 'ACIS SAT (3D geometry)' },
  x_t:     { app: 'Parasolid Text' },
  x_b:     { app: 'Parasolid Binary' },

  // 3D mesh
  stl:     { app: 'STL (3D printing)' },
  obj:     { app: 'Wavefront OBJ', chunk: 'threed' },
  fbx:     { app: 'Autodesk FBX' },
  gltf:    { app: 'glTF 3D Scene', chunk: 'threed' },
  glb:     { app: 'glTF Binary' },
  ply:     { app: 'PLY Point Cloud / Mesh', chunk: 'threed' },
  usdz:    { app: 'Universal Scene Description (Apple AR)' },
  usd:     { app: 'Universal Scene Description' },
  zcode:   { app: 'Zortrax Z-SUITE (compiled print)' },
  usda:    { app: 'Universal Scene Description ASCII' },

  // Blender
  blend:   { app: 'Blender' },

  // CATIA / Creo / NX
  catpart:    { app: 'CATIA Part' },
  catproduct: { app: 'CATIA Product' },
  cgr:        { app: 'CATIA Graphics' },
  prt:        { app: 'Creo / Pro-E / NX Part' },
  asm:        { app: 'Creo / Pro-E Assembly' },

  // EDA / PCB
  brd:     { app: 'Eagle / Altium PCB' },
  sch:     { app: 'Eagle / KiCad Schematic' },
  kicad_pcb: { app: 'KiCad PCB' },

  // Microsoft Office (binary)
  doc:     { app: 'Microsoft Word' },
  xls:     { app: 'Microsoft Excel' },
  ppt:     { app: 'Microsoft PowerPoint' },

  // Microsoft Office (Open XML - ZIP-based)
  docx:    { app: 'Microsoft Word', zip: true },
  xlsx:    { app: 'Microsoft Excel', zip: true },
  pptx:    { app: 'Microsoft PowerPoint', zip: true },

  // Apple
  pages:   { app: 'Apple Pages', zip: true },
  numbers: { app: 'Apple Numbers', zip: true },
  keynote: { app: 'Apple Keynote', zip: true },
  sketch:  { app: 'Sketch', zip: true },

  // 3D printing
  '3mf':   { app: '3D Manufacturing Format', zip: true, chunk: 'threed' },
  amf:     { app: 'Additive Manufacturing File', chunk: 'threed' },
  idea:    { app: 'Raise3D ideaMaker', chunk: 'threed' },

  // Figma (local)
  fig:     { app: 'Figma', chunk: 'image' },

  // Substance
  spp:     { app: 'Adobe Substance Painter' },
  sbsar:   { app: 'Adobe Substance Archive' },
  sbs:     { app: 'Adobe Substance Designer' },

  // Paint.NET
  pdn:     { app: 'Paint.NET' },

  // Microsoft Office (presentations)
  ppsx:    { app: 'Microsoft PowerPoint Show', zip: true },

  // OpenDocument
  odt:     { app: 'OpenDocument Text (LibreOffice Writer)', zip: true },
  ods:     { app: 'OpenDocument Spreadsheet (LibreOffice Calc)', zip: true },
  odp:     { app: 'OpenDocument Presentation (LibreOffice Impress)', zip: true },
  odg:     { app: 'OpenDocument Graphics (LibreOffice Draw)', zip: true },

  // GIMP
  xcf:     { app: 'GIMP' },

  // Affinity
  afphoto: { app: 'Affinity Photo' },
  afdesign:{ app: 'Affinity Designer' },
  afpub:   { app: 'Affinity Publisher' },

  // Procreate
  procreate: { app: 'Procreate', zip: true },

  // Krita
  kra:     { app: 'Krita', zip: true },

  // DaVinci Resolve
  drp:     { app: 'DaVinci Resolve Project' },
  drt:     { app: 'DaVinci Resolve Timeline' },

  // Vegas Pro (Sony / MAGIX)
  veg:     { app: 'VEGAS Pro Project' },
  vf:      { app: 'VEGAS Pro Project Backup' },

  // Wondershare Filmora
  wfp:     { app: 'Wondershare Filmora Project' },

  // SharePoint solution package (a renamed CAB, not a Filmora project)
  wsp:     { app: 'SharePoint Solution Package', chunk: 'archive' },

  // Music production
  als:     { app: 'Ableton Live Set' },
  alp:     { app: 'Ableton Live Pack' },
  flp:     { app: 'FL Studio Project' },
  rpp:     { app: 'Reaper Project', parse: 'text' },
  'rpp-bak': { app: 'Reaper Project Backup', parse: 'text' },
  logic:   { app: 'Logic Pro Project' },
  logicx:  { app: 'Logic Pro X Project' },
  ptx:     { app: 'Pro Tools Session' },
  cpr:     { app: 'Steinberg Cubase Project' },
  band:    { app: 'GarageBand Project' },

  // Archives
  rar:     { app: 'RAR Archive' },
  '7z':    { app: '7-Zip Archive' },
  tar:     { app: 'Tar Archive', chunk: 'archive' },
  gz:      { app: 'Gzip Archive', chunk: 'archive' },
  bz2:     { app: 'Bzip2 Archive', chunk: 'archive' },
  xz:      { app: 'XZ Archive', chunk: 'archive' },
  zst:     { app: 'Zstandard Archive', chunk: 'archive' },
  tgz:     { app: 'Gzipped Tar Archive', chunk: 'archive' },

  // Disk images
  iso:     { app: 'ISO Disk Image' },
  img:     { app: 'Disk Image' },
  vhd:     { app: 'Virtual Hard Disk (Hyper-V)' },
  vhdx:    { app: 'Virtual Hard Disk v2 (Hyper-V)' },
  vmdk:    { app: 'VMware Virtual Disk' },
  qcow2:   { app: 'QEMU Copy-on-Write Disk' },
  vdi:     { app: 'VirtualBox Disk Image' },
  adi:     { app: 'Active@ Disk Image Backup' },   // parsed locally (parseAdi)

  // Fonts
  ttf:     { app: 'TrueType Font' },
  otf:     { app: 'OpenType Font' },
  woff:    { app: 'Web Open Font Format' },
  woff2:   { app: 'Web Open Font Format 2' },
  ttc:     { app: 'TrueType Font Collection' },
  glif:    { app: 'UFO Glyph (GLIF)', parse: 'text' },

  // e-books
  epub:    { app: 'EPUB e-book', zip: true },
  mobi:    { app: 'Kindle / Mobipocket e-book' },
  azw3:    { app: 'Kindle Format 8 e-book' },
  azw:     { app: 'Kindle e-book' },
  fb2:     { app: 'FictionBook e-book', parse: 'xml' },
  djvu:    { app: 'DjVu Document' },

  // Subtitles
  srt:     { app: 'SubRip Subtitle', parse: 'text' },
  vtt:     { app: 'WebVTT Subtitle', parse: 'text' },
  ass:     { app: 'Advanced SubStation Alpha', parse: 'text' },
  ssa:     { app: 'SubStation Alpha', parse: 'text' },
  sub:     { app: 'MicroDVD / VobSub Subtitle', parse: 'text' },

  // Database
  // .dcb is ambiguous (see EXT_VARIANTS in core/formats.ts): the Concordance
  // litigation database is the one that is still met in the wild, and the card
  // renames itself when the bytes prove one of the others.
  dcb:     { app: 'Concordance Database' },
  sqlite:  { app: 'SQLite Database' },
  sqlite3: { app: 'SQLite Database' },
  db3:     { app: 'SQLite Database' },
  db:      { app: 'Database File' },
  'sqlite-wal':  { app: 'SQLite Write-Ahead Log' },
  'sqlite3-wal': { app: 'SQLite Write-Ahead Log' },
  'db-wal':      { app: 'SQLite Write-Ahead Log' },
  'db3-wal':     { app: 'SQLite Write-Ahead Log' },
  'sqlite-shm':  { app: 'SQLite Shared-Memory Index' },
  'sqlite3-shm': { app: 'SQLite Shared-Memory Index' },
  'db-shm':      { app: 'SQLite Shared-Memory Index' },
  'db3-shm':     { app: 'SQLite Shared-Memory Index' },
  mdb:     { app: 'Microsoft Access Database' },
  accdb:   { app: 'Microsoft Access Database' },

  // GIS / Mapping
  shp:     { app: 'ESRI Shapefile', chunk: 'geodata' },
  kml:     { app: 'Keyhole Markup Language (Google Earth)', parse: 'xml' },
  kmz:     { app: 'KML Archive (Google Earth)', zip: true },
  gpx:     { app: 'GPS Exchange Format', parse: 'xml' },
  geojson: { app: 'GeoJSON', parse: 'text' },

  // Game engines
  unitypackage: { app: 'Unity Asset Package' },
  uasset:  { app: 'Unreal Engine Asset' },
  umap:    { app: 'Unreal Engine Map' },
  godot:   { app: 'Godot Project', parse: 'text' },
  tscn:    { app: 'Godot Scene', parse: 'text' },
  tres:    { app: 'Godot Resource', parse: 'text' },
  // .scn is shared by Godot's BINARY scene (RSRC magic), several strategy games'
  // scenarios and a couple of plain-text scene formats - so no parse hint here,
  // and EXT_VARIANTS names whichever the bytes prove.
  scn:     { app: 'Scene / Scenario File' },
  cpmmodel: { app: 'Custom Player Models Model' },

  // Torrent
  torrent: { app: 'BitTorrent Metainfo' },

  // CNC / 3D printing
  gcode:   { app: 'G-Code (CNC / 3D printing)', parse: 'text' },
  gco:     { app: 'G-Code (CNC / 3D printing)', parse: 'text' },
  nc:      { app: 'G-Code (CNC)', parse: 'text' },
  ngc:     { app: 'G-Code (CNC)', parse: 'text' },
  tap:     { app: 'G-Code (CNC)', parse: 'text' },
  cnc:     { app: 'G-Code (CNC)', parse: 'text' },

  // Log files
  log:     { app: 'Log File', parse: 'text' },

  // Config
  toml:    { app: 'TOML Config', parse: 'text' },
  ini:     { app: 'INI Config', parse: 'text' },
  env:     { app: 'Environment Variables', parse: 'text' },
  conf:    { app: 'Configuration File', parse: 'text', chunk: 'security' },
  cfg:     { app: 'Configuration File', parse: 'text' },
  properties: { app: 'Java Properties', parse: 'text' },

  // Executables
  exe:     { app: 'Windows Executable' },
  dll:     { app: 'Windows Dynamic Library' },
  msi:     { app: 'Windows Installer' },
  apk:     { app: 'Android Application' },
  ipa:     { app: 'iOS Application', zip: true },
  dmg:     { app: 'macOS Disk Image' },
  appimage:{ app: 'Linux AppImage' },

  // Web
  html:    { app: 'HTML Document', parse: 'html' },
  htm:     { app: 'HTML Document', parse: 'html' },
  css:     { app: 'CSS Stylesheet', parse: 'text' },
  js:      { app: 'JavaScript', parse: 'text' },
  mjs:     { app: 'JavaScript Module', parse: 'text' },
  ts:      { app: 'TypeScript', parse: 'text' },
  tsx:     { app: 'TypeScript JSX', parse: 'text' },
  jsx:     { app: 'React JSX', parse: 'text' },
  json:    { app: 'JSON', parse: 'text' },
  yaml:    { app: 'YAML', parse: 'text' },
  yml:     { app: 'YAML', parse: 'text' },
  xml:     { app: 'XML Document', parse: 'xml' },
  md:      { app: 'Markdown', parse: 'text' },
  txt:     { app: 'Plain Text', parse: 'text' },

  // Shell / scripts
  ps1:     { app: 'PowerShell Script', parse: 'text', chunk: 'dev' },
  psm1:    { app: 'PowerShell Module', parse: 'text', chunk: 'dev' },
  psd1:    { app: 'PowerShell Data File', parse: 'text', chunk: 'dev' },
  bat:     { app: 'Windows Batch Script', parse: 'text', chunk: 'dev' },
  cmd:     { app: 'Windows Command Script', parse: 'text', chunk: 'dev' },

  // Source code (plain-text source preview - the files that fill a code repo)
  c:       { app: 'C Source', parse: 'text' },
  h:       { app: 'C / C++ Header', parse: 'text' },
  cc:      { app: 'C++ Source', parse: 'text' },
  cpp:     { app: 'C++ Source', parse: 'text' },
  cxx:     { app: 'C++ Source', parse: 'text' },
  hpp:     { app: 'C++ Header', parse: 'text' },
  hh:      { app: 'C++ Header', parse: 'text' },
  hxx:     { app: 'C++ Header', parse: 'text' },
  ino:     { app: 'Arduino Sketch', parse: 'text' },
  cs:      { app: 'C# Source', parse: 'text' },
  java:    { app: 'Java Source', parse: 'text' },
  kt:      { app: 'Kotlin Source', parse: 'text' },
  kts:     { app: 'Kotlin Script', parse: 'text' },
  go:      { app: 'Go Source', parse: 'text' },
  rs:      { app: 'Rust Source', parse: 'text' },
  py:      { app: 'Python Source', parse: 'text' },
  pyw:     { app: 'Python Source', parse: 'text' },
  rb:      { app: 'Ruby Source', parse: 'text' },
  php:     { app: 'PHP Source', parse: 'text' },
  swift:   { app: 'Swift Source', parse: 'text' },
  scala:   { app: 'Scala Source', parse: 'text' },
  lua:     { app: 'Lua Script', parse: 'text' },
  pl:      { app: 'Perl Source', parse: 'text' },
  pm:      { app: 'Perl Module', parse: 'text' },
  r:       { app: 'R Source', parse: 'text' },
  dart:    { app: 'Dart Source', parse: 'text' },
  groovy:  { app: 'Groovy Source', parse: 'text' },
  vb:      { app: 'Visual Basic Source', parse: 'text' },
  mm:      { app: 'Objective-C++ Source', parse: 'text' },
  hmm:     { app: 'Objective-C++ Header', parse: 'text' },

  // GPU shaders (plain-text source preview)
  glsl:    { app: 'GLSL Shader', parse: 'text' },
  vert:    { app: 'GLSL Vertex Shader', parse: 'text' },
  frag:    { app: 'GLSL Fragment Shader', parse: 'text' },
  comp:    { app: 'GLSL Compute Shader', parse: 'text' },
  hlsl:    { app: 'HLSL Shader', parse: 'text' },
  fs:      { app: 'GLSL Fragment Shader', parse: 'text' },
  vs:      { app: 'GLSL Vertex Shader', parse: 'text' },
  gs:      { app: 'GLSL Geometry Shader', parse: 'text' },

  // Shell scripts (plain-text source preview)
  sh:      { app: 'Shell Script', parse: 'text' },
  bash:    { app: 'Bash Script', parse: 'text' },
  zsh:     { app: 'Zsh Script', parse: 'text' },
  fish:    { app: 'Fish Script', parse: 'text' },

  // Build systems, make and project files (plain-text source preview)
  cmake:   { app: 'CMake Script', parse: 'text' },
  mk:      { app: 'Makefile Fragment', parse: 'text' },
  mak:     { app: 'Makefile', parse: 'text' },
  make:    { app: 'Makefile', parse: 'text' },
  ninja:   { app: 'Ninja Build File', parse: 'text' },
  in:      { app: 'Autoconf Template', parse: 'text' },
  inc:     { app: 'Include File', parse: 'text' },
  am:      { app: 'Automake File', parse: 'text' },
  ac:      { app: 'Autoconf Script', parse: 'text' },
  m4:      { app: 'M4 Macro File', parse: 'text' },
  pro:     { app: 'qmake Project', parse: 'text' },
  pri:     { app: 'qmake Include', parse: 'text' },
  qrc:     { app: 'Qt Resource Collection', parse: 'xml' },
  rc:      { app: 'Resource Script', parse: 'text' },
  def:     { app: 'Module Definition File', parse: 'text' },
  spec:    { app: 'Spec File', parse: 'text' },
  dox:     { app: 'Doxygen Config', parse: 'text' },
  doxygen: { app: 'Doxygen Config', parse: 'text' },
  jam:     { app: 'Boost.Jam Build Script', parse: 'text' },
  build:   { app: 'Meson Build Script', parse: 'text' },
  skip:    { app: 'Skipped-Test Marker', parse: 'text' },
  man:     { app: 'Unix Manual Page', parse: 'text' },

  // Tool dotfiles (ignore lists, attributes, formatter / linter configs)
  gitignore:      { app: 'Git Ignore Rules', parse: 'text' },
  gitattributes:  { app: 'Git Attributes', parse: 'text' },
  gitmodules:     { app: 'Git Submodules', parse: 'text' },
  dockerignore:   { app: 'Docker Ignore Rules', parse: 'text' },
  npmignore:      { app: 'npm Ignore Rules', parse: 'text' },
  eslintignore:   { app: 'ESLint Ignore Rules', parse: 'text' },
  prettierignore: { app: 'Prettier Ignore Rules', parse: 'text' },
  cursorignore:   { app: 'Cursor Ignore Rules', parse: 'text' },
  'clang-format': { app: 'Clang-Format Config', parse: 'text' },
  'clang-tidy':   { app: 'Clang-Tidy Config', parse: 'text' },

  // Web styles / components, localisation, manuals and licence text
  less:    { app: 'Less Stylesheet', parse: 'text' },
  scss:    { app: 'Sass Stylesheet', parse: 'text' },
  svelte:  { app: 'Svelte Component', parse: 'text' },
  po:      { app: 'gettext Translation', parse: 'text' },
  pot:     { app: 'gettext Template', parse: 'text' },
  entitlements: { app: 'Apple Entitlements', parse: 'xml' },
  copying: { app: 'Licence Text', parse: 'text' },
  readme:  { app: 'Readme File', parse: 'text' },
  lesser:  { app: 'Licence Text', parse: 'text' },

  // More shaders, source, web and dotfiles (plain-text source preview)
  fsh:     { app: 'OpenGL Fragment Shader', parse: 'text' },
  vsh:     { app: 'OpenGL Vertex Shader', parse: 'text' },
  geom:    { app: 'GLSL Geometry Shader', parse: 'text' },
  pyx:     { app: 'Cython Source', parse: 'text' },
  sample:  { app: 'Git Hook Sample', parse: 'text' },
  eslintrc:  { app: 'ESLint Config', parse: 'text' },
  yarnclean: { app: 'Yarn Clean List', parse: 'text' },
  aspx:    { app: 'ASP.NET Web Page', parse: 'text' },
  asp:     { app: 'Classic ASP Page', parse: 'text', chunk: 'dev' },
  idl:     { app: 'Interface Definition (IDL)', parse: 'text', chunk: 'dev' },
  pc:      { app: 'pkg-config Metadata', parse: 'text', chunk: 'dev' },
  dsd:     { app: 'DraStic Shader', parse: 'text', chunk: 'dev' },
  template: { app: 'Text Template', parse: 'text', chunk: 'dev' },
  static:  { app: 'Static Asset / Fixture', parse: 'text' },
  agc:     { app: 'Google Camera Config', parse: 'xml', chunk: 'osmisc' },
  obb:     { app: 'Android OBB Expansion', chunk: 'archive' },
  penc:    { app: 'Samsung Encrypted Package', chunk: 'osmisc' },
  enc:     { app: 'Encrypted File', chunk: 'osmisc' },
  bk:      { app: 'Backup Container', chunk: 'osmisc' },

  // Config, language and info text
  config:  { app: 'Configuration File', parse: 'text' },
  info:    { app: 'Info Text File', parse: 'text' },
  inf:     { app: 'Windows Setup Information', parse: 'text' },
  lst:     { app: 'List / Index File', parse: 'text', chunk: 'osmisc' },
  lang:    { app: 'Language Strings', parse: 'text' },
  lng:     { app: 'Language File', parse: 'text' },

  // Project / config files that are really JSON or XML (shown as source)
  mcmeta:  { app: 'Minecraft Asset Metadata', parse: 'text' },
  uproject: { app: 'Unreal Engine Project', parse: 'text' },
  uplugin: { app: 'Unreal Engine Plugin', parse: 'text' },
  kicad_pro: { app: 'KiCad Project', parse: 'text' },
  kicad_prl: { app: 'KiCad Project Local Settings', parse: 'text' },
  kicad_sch: { app: 'KiCad Schematic', parse: 'text' },
  tps:     { app: 'Unreal Third-Party Notice', parse: 'xml' },
  browser: { app: 'ASP.NET Browser Definition', parse: 'xml' },

  // Game-engine binaries (identification only)
  ubulk:   { app: 'Unreal Bulk Data' },
  ufont:   { app: 'Unreal Font' },
  locmeta: { app: 'Unreal Localization Metadata' },
  locres:  { app: 'Unreal Localization Resource' },
  ushaderbytecode: { app: 'Unreal Shader Bytecode' },
  ress:    { app: 'Unity Resource Stream' },
  bk2:     { app: 'Bink Video 2' },

  // Fonts, modules, paint, i18n data and backups (identification only)
  eot:     { app: 'Embedded OpenType Font' },
  pyd:     { app: 'Python Extension Module' },
  mdp:     { app: 'MediBang Paint Document' },
  icu:     { app: 'ICU Data' },
  pdsbak:  { app: 'Proteus Design Backup' },
  bak:     { app: 'Backup File' },
  old:     { app: 'Backup File' },

  // Developer / data / serialization (lazy parser chunk: parsers-dev.js)
  jwt:     { app: 'JSON Web Token', chunk: 'dev' },
  har:     { app: 'HTTP Archive', chunk: 'dev' },
  ipynb:   { app: 'Jupyter Notebook', chunk: 'dev' },
  jsonl:   { app: 'JSON Lines', chunk: 'dev' },
  ndjson:  { app: 'Newline-delimited JSON', chunk: 'dev' },
  diff:    { app: 'Unified Diff', chunk: 'dev' },
  patch:   { app: 'Patch File', chunk: 'dev' },
  wasm:    { app: 'WebAssembly Binary', chunk: 'dev' },
  class:   { app: 'Java Class File', chunk: 'dev' },
  npy:     { app: 'NumPy Array', chunk: 'dev' },
  safetensors: { app: 'Safetensors Model', chunk: 'dev' },
  gguf:    { app: 'GGUF Model (GGML)', chunk: 'dev' },
  map:     { app: 'Source Map', chunk: 'dev' },
  sql:     { app: 'SQL Dump', chunk: 'dev' },
  sln:     { app: 'Visual Studio Solution', chunk: 'dev' },
  slnx:    { app: 'Visual Studio Solution (XML)', chunk: 'dev', parse: 'xml' },
  csproj:  { app: '.NET Project (C#)', chunk: 'dev' },
  vbproj:  { app: '.NET Project (VB)', chunk: 'dev' },
  fsproj:  { app: '.NET Project (F#)', chunk: 'dev' },
  vcxproj: { app: 'Visual C++ Project', chunk: 'dev' },
  gradle:  { app: 'Gradle Build Script', chunk: 'dev' },
  tf:      { app: 'Terraform Config', chunk: 'dev' },
  tfstate: { app: 'Terraform State', chunk: 'dev' },
  editorconfig: { app: 'EditorConfig', chunk: 'dev' },
  proto:   { app: 'Protocol Buffers Schema', chunk: 'dev' },
  graphql: { app: 'GraphQL Schema', chunk: 'dev' },
  gql:     { app: 'GraphQL Schema', chunk: 'dev' },
  sarif:   { app: 'SARIF Analysis Report', chunk: 'dev' },
  pyc:     { app: 'Python Bytecode', chunk: 'dev' },
  plist:   { app: 'Apple Property List', chunk: 'dev' },

  // Archives / packages / installers (lazy parser chunk: parsers-archive.js)
  lz4:     { app: 'LZ4 Frame', chunk: 'archive' },
  lzma:    { app: 'LZMA Stream', chunk: 'archive' },
  txz:     { app: 'XZ Tarball', chunk: 'archive' },
  tzst:    { app: 'Zstandard Tarball', chunk: 'archive' },
  z:       { app: 'compress (.Z)', chunk: 'archive' },
  cpio:    { app: 'cpio Archive', chunk: 'archive' },
  a:       { app: 'Unix ar / Static Library', chunk: 'archive' },
  lib:     { app: 'Microsoft COFF Library', chunk: 'archive' },
  whl:     { app: 'Python Wheel', chunk: 'archive' },
  nupkg:   { app: 'NuGet Package', chunk: 'archive' },
  crx:     { app: 'Chrome Extension', chunk: 'archive' },
  xpi:     { app: 'Firefox Add-on', chunk: 'archive' },
  vsix:    { app: 'VS Code Extension', chunk: 'archive' },
  asar:    { app: 'Electron ASAR', chunk: 'archive' },
  appx:    { app: 'Windows App Package', chunk: 'archive' },
  msix:    { app: 'Windows App Package', chunk: 'archive' },
  apkg:    { app: 'Anki Deck Package', chunk: 'archive' },
  xapk:    { app: 'Android App Bundle', zip: true, chunk: 'archive' },
  apkm:    { app: 'APKMirror App Bundle', zip: true, chunk: 'archive' },
  apks:    { app: 'Android App Set', zip: true, chunk: 'archive' },
  conda:   { app: 'Conda Package', chunk: 'archive' },
  deb:     { app: 'Debian Package', chunk: 'archive' },
  rpm:     { app: 'RPM Package', chunk: 'archive' },
  gem:     { app: 'RubyGems Package', chunk: 'archive' },
  cab:     { app: 'Microsoft Cabinet', chunk: 'archive' },
  ace:     { app: 'ACE Archive', chunk: 'archive' },
  arj:     { app: 'ARJ Archive', chunk: 'archive' },
  lzh:     { app: 'LHA / LZH Archive', chunk: 'archive' },
  lha:     { app: 'LHA / LZH Archive', chunk: 'archive' },
  zoo:     { app: 'Zoo Archive', chunk: 'archive' },
  arc:     { app: 'ARC Archive', chunk: 'archive' },

  // Email / calendar / contacts / PIM (lazy parser chunk: parsers-email.js)
  eml:     { app: 'Email Message (MIME)', chunk: 'email' },
  emlx:    { app: 'Apple Mail Message', chunk: 'email' },
  mbox:    { app: 'Mbox Mailbox', chunk: 'email' },
  ics:     { app: 'iCalendar', chunk: 'email' },
  ical:    { app: 'iCalendar', chunk: 'email' },
  ifb:     { app: 'iCalendar Free/Busy', chunk: 'email' },
  vcf:     { app: 'vCard Contact', chunk: 'email' },
  vcard:   { app: 'vCard Contact', chunk: 'email' },
  vcs:     { app: 'vCalendar 1.0', chunk: 'email' },
  ldif:    { app: 'LDIF (LDAP Export)', chunk: 'email' },
  contact: { app: 'Windows Contact', chunk: 'email' },
  msg:     { app: 'Outlook Message', chunk: 'email' },
  pst:     { app: 'Outlook Personal Store', chunk: 'email' },
  ost:     { app: 'Outlook Offline Store', chunk: 'email' },
  edb:     { app: 'Exchange / ESE Database', chunk: 'email' },
  dbx:     { app: 'Outlook Express Database', chunk: 'email' },

  // Security / crypto / keys / certs / forensics (lazy parser chunk: parsers-security.js)
  key:     { app: 'PEM Private/Public Key', chunk: 'security' },
  pub:     { app: 'OpenSSH Public Key', chunk: 'security' },
  p8:      { app: 'PKCS#8 Key', chunk: 'security' },
  csr:     { app: 'PKCS#10 Cert Request', chunk: 'security' },
  crl:     { app: 'X.509 CRL', chunk: 'security' },
  p7b:     { app: 'PKCS#7 Cert Bundle', chunk: 'security' },
  p7c:     { app: 'PKCS#7 Cert Bundle', chunk: 'security' },
  ppk:     { app: 'PuTTY Private Key', chunk: 'security' },
  ovpn:    { app: 'OpenVPN Profile', chunk: 'security' },
  wg:      { app: 'WireGuard Config', chunk: 'security' },
  jks:     { app: 'Java KeyStore', chunk: 'security' },
  keystore:{ app: 'Java KeyStore', chunk: 'security' },
  jceks:   { app: 'Java KeyStore (JCEKS)', chunk: 'security' },
  known_hosts: { app: 'OpenSSH known_hosts', chunk: 'security' },
  authorized_keys: { app: 'OpenSSH authorized_keys', chunk: 'security' },
  mobileconfig: { app: 'Apple Config Profile', chunk: 'security' },
  mobileprovision: { app: 'Apple Provisioning Profile', chunk: 'security' },
  reg:     { app: 'Windows Registry Export', chunk: 'security' },
  pcap:    { app: 'libpcap Capture', chunk: 'security' },
  cap:     { app: 'libpcap Capture', chunk: 'security' },
  pcapng:  { app: 'PCAP Next Generation', chunk: 'security' },
  ntar:    { app: 'PCAP Next Generation', chunk: 'security' },
  p12:     { app: 'PKCS#12 / PFX Bundle', chunk: 'security' },
  pfx:     { app: 'PKCS#12 / PFX Bundle', chunk: 'security' },
  kdbx:    { app: 'KeePass Database', chunk: 'security' },
  evtx:    { app: 'Windows Event Log', chunk: 'security' },
  pf:      { app: 'Windows Prefetch', chunk: 'security' },
  hive:    { app: 'Registry Hive', chunk: 'security' },
  dmp:     { app: 'Crash / Memory Dump', chunk: 'security' },
  e01:     { app: 'EnCase Forensic Image', chunk: 'security' },
  etl:     { app: 'Event Trace Log', chunk: 'security' },

  // REDengine 4 (Cyberpunk 2077 / The Witcher) - lazy chunk parsers-gaming.js.
  // oodledict / redshadercache / innouninstall are virtual keys: their real
  // extensions (.bin / .cache / .dat) are too generic to route by name, so app.js
  // content-gates them by magic and routes via sniffedExt.
  archive:          { app: 'REDengine 4 archive (Cyberpunk 2077)', chunk: 'gaming' },
  redscripts:       { app: 'REDengine compiled scripts', chunk: 'gaming' },
  addcont_keystone: { app: 'REDengine add-on content keystone', chunk: 'gaming' },
  script:           { app: 'REDengine / redscript source', parse: 'text' },
  tweak:            { app: 'REDengine TweakXL source', parse: 'text' },
  rne:              { app: 'Renamed DLL (REDengine / Cyberpunk)' },
  oodledict:        { app: 'Oodle-compressed data (REDengine)', chunk: 'gaming' },
  redshadercache:   { app: 'REDengine shader cache', chunk: 'gaming' },
  innouninstall:    { app: 'Inno Setup uninstall log', chunk: 'gaming' },

  // Source text long-tail (Python venv / scientific stacks) - shown as source.
  // pythonpath is a virtual key: .pth is content-gated (text vs PyTorch binary).
  pyi:  { app: 'Python type stub', parse: 'text' },
  pxi:  { app: 'Cython include', parse: 'text' },
  pxd:  { app: 'Cython definition file', parse: 'text' },
  pyf:  { app: 'F2PY interface (Fortran/Python)', parse: 'text' },
  pys:  { app: 'Python script', parse: 'text' },
  vbs:  { app: 'VBScript', parse: 'text' },
  f90:  { app: 'Fortran 90 source', parse: 'text' },
  f95:  { app: 'Fortran 95 source', parse: 'text' },
  f:    { app: 'Fortran source (fixed-form)', parse: 'text' },
  sct:  { app: 'Windows Script Component', parse: 'xml' },
  rng:  { app: 'RELAX NG schema', parse: 'xml' },
  xsl:  { app: 'XSLT stylesheet', parse: 'xml' },
  cnf:  { app: 'Configuration file', parse: 'text' },
  zi:   { app: 'tz database source', parse: 'text' },
  '1':  { app: 'Unix manual page (troff)', parse: 'text' },
  pythonpath: { app: 'Python path configuration (.pth)', parse: 'text' },

  // Cross-platform binaries, ML & misc (lazy chunk parsers-dev.js). citationcff
  // is a virtual key: .cff is content-gated (YAML citation vs binary CFF font).
  onnx:   { app: 'ONNX neural-network model', chunk: 'dev' },
  trt:    { app: 'NVIDIA TensorRT engine' },
  node:   { app: 'Native add-on module (.node)', chunk: 'dev' },
  dylib:  { app: 'macOS dynamic library', chunk: 'dev' },
  ldb:    { app: 'LevelDB table', chunk: 'dev' },
  rev:    { app: 'Git pack reverse index', chunk: 'dev' },
  citationcff: { app: 'Citation File Format (CITATION.cff)', parse: 'text' },
  rsp:    { app: 'Compiler response file', parse: 'text' },
  cgp:    { app: 'Pattern / grid data (.cgp)', parse: 'text' },
  chroma: { app: 'Razer Chroma animation' },
  stamp:  { app: 'Build stamp / marker' },

  // Marathon / Aleph One (lazy chunk parsers-gaming.js). Keys are lowercase
  // because extFromName lowercases (.sceA -> scea). .mml is XML text.
  scen: { app: 'Marathon / Aleph One scenario', chunk: 'gaming' },
  scea: { app: 'Marathon / Aleph One scenario', chunk: 'gaming' },
  appl: { app: 'Marathon / Aleph One plugin data', chunk: 'gaming' },
  phys: { app: 'Marathon / Aleph One physics', chunk: 'gaming' },
  phya: { app: 'Marathon / Aleph One physics', chunk: 'gaming' },
  shps: { app: 'Marathon / Aleph One shapes', chunk: 'gaming' },
  shpa: { app: 'Marathon / Aleph One shapes', chunk: 'gaming' },
  sndz: { app: 'Marathon / Aleph One sounds', chunk: 'gaming' },
  snda: { app: 'Marathon / Aleph One sounds', chunk: 'gaming' },
  fila: { app: 'Marathon / Aleph One film', chunk: 'gaming' },
  imga: { app: 'Marathon / Aleph One images', chunk: 'gaming' },
  mml:  { app: 'Aleph One MML config', parse: 'xml' },

  // Unity / IL2CPP - lazy chunk parsers-gaming.js. il2cppmeta / addrcatalog /
  // unitymanifest are virtual keys: their real extensions (.dat / .bin /
  // .manifest) are content-gated by app.js.
  usym:          { app: 'IL2CPP symbol map', chunk: 'gaming' },
  pd_:           { app: '.NET assembly metadata (renamed)', chunk: 'gaming' },
  hfthumb:       { app: 'House Flipper thumbnail', chunk: 'gaming' },
  shadervariants: { app: 'Unity shader variant collection', parse: 'text' },
  shader:        { app: 'Shader (ShaderLab / GPU shader)', parse: 'text' },
  il2cppmeta:    { app: 'IL2CPP global metadata', chunk: 'gaming' },
  addrcatalog:   { app: 'Unity Addressables catalog', chunk: 'gaming' },
  unitymanifest: { app: 'Unity asset bundle manifest', chunk: 'gaming', parse: 'text' },
  hash:          { app: 'Hash / checksum', parse: 'text' },

  // Source 2 (Valve: Deadlock / CS2 / Dota 2) - text assets. chunk parser
  // surfaces the KV3 header / gameinfo, parse:'text' shows the source.
  // valveres is a virtual key: .res is content-gated by app.js (text vs binary).
  gi:            { app: 'Source 2 game info (gameinfo.gi)', chunk: 'gaming', parse: 'text' },
  kv3:           { app: 'Valve KeyValues3', chunk: 'gaming', parse: 'text' },
  vcfg:          { app: 'Source 2 config', chunk: 'gaming', parse: 'text' },
  vqlayout:      { app: 'Source 2 tools layout', chunk: 'gaming', parse: 'text' },
  vsc:           { app: 'Source 2 style colours', chunk: 'gaming', parse: 'text' },
  qss:           { app: 'Qt style sheet', chunk: 'gaming', parse: 'text' },
  signatures:    { app: 'Source 2 function signatures', chunk: 'gaming', parse: 'text' },
  vsnd_template: { app: 'Source 2 sound-event template', chunk: 'gaming', parse: 'text' },
  vnm_template:  { app: 'Source 2 node-graph template', chunk: 'gaming', parse: 'text' },
  mks_template:  { app: 'Source 2 sheet template', chunk: 'gaming', parse: 'text' },
  valveres:      { app: 'Valve resource / UI layout', chunk: 'gaming', parse: 'text' },

  // Game ROMs / engine assets (lazy parser chunk: parsers-gaming.js)
  nes:     { app: 'NES ROM (iNES)', chunk: 'gaming' },
  gb:      { app: 'Game Boy ROM', chunk: 'gaming' },
  gbc:     { app: 'Game Boy Color ROM', chunk: 'gaming' },
  gba:     { app: 'Game Boy Advance ROM', chunk: 'gaming' },
  sfc:     { app: 'SNES ROM', chunk: 'gaming' },
  smc:     { app: 'SNES ROM (copier)', chunk: 'gaming' },
  nds:     { app: 'Nintendo DS ROM', chunk: 'gaming' },
  dsi:     { app: 'Nintendo DSi ROM', chunk: 'gaming' },
  z64:     { app: 'Nintendo 64 ROM (big-endian)', chunk: 'gaming' },
  n64:     { app: 'Nintendo 64 ROM (little-endian)', chunk: 'gaming' },
  v64:     { app: 'Nintendo 64 ROM (byteswapped)', chunk: 'gaming' },
  gen:     { app: 'Sega Genesis / Mega Drive ROM', chunk: 'gaming' },
  smd:     { app: 'Sega Mega Drive ROM (SMD)', chunk: 'gaming' },
  ips:     { app: 'IPS ROM Patch', chunk: 'gaming' },
  bps:     { app: 'BPS ROM Patch', chunk: 'gaming' },
  ups:     { app: 'UPS ROM Patch', chunk: 'gaming' },
  ppf:     { app: 'PPF ROM/CD Patch', chunk: 'gaming' },
  wad:     { app: 'Doom WAD', chunk: 'gaming' },
  nbt:     { app: 'Minecraft NBT Data', chunk: 'gaming' },
  schematic: { app: 'Minecraft Schematic', chunk: 'gaming' },
  schem:   { app: 'Minecraft Schematic (Sponge)', chunk: 'gaming' },
  litematic: { app: 'Litematica Schematic', chunk: 'gaming' },
  mcworld: { app: 'Minecraft Bedrock World', chunk: 'gaming' },
  mcpack:  { app: 'Minecraft Bedrock Pack', chunk: 'gaming' },
  mcaddon: { app: 'Minecraft Bedrock Add-on', chunk: 'gaming' },
  ase:     { app: 'Aseprite Sprite', chunk: 'gaming' },
  aseprite:{ app: 'Aseprite Sprite', chunk: 'gaming' },
  pck:     { app: 'Godot Resource Pack', chunk: 'gaming' },
  pak:     { app: 'Quake PACK Archive', chunk: 'gaming' },
  pk3:     { app: 'id Tech 3 Archive (ZIP)', chunk: 'gaming' },
  pk4:     { app: 'id Tech 4 Archive (ZIP)', chunk: 'gaming' },
  bsp:     { app: 'Compiled Map (BSP)', chunk: 'gaming' },
  vpk:     { app: 'Valve Pak', chunk: 'gaming' },
  vtf:     { app: 'Valve Texture', chunk: 'gaming' },
  vmt:     { app: 'Valve Material', chunk: 'gaming' },
  ktx:     { app: 'KTX GPU Texture', chunk: 'gaming' },
  ktx2:    { app: 'KTX2 GPU Texture', chunk: 'gaming' },
  tmx:     { app: 'Tiled Map (XML)', chunk: 'gaming' },
  tmj:     { app: 'Tiled Map (JSON)', chunk: 'gaming' },
  tsj:     { app: 'Tiled Tileset (JSON)', chunk: 'gaming' },
  love:    { app: 'LÖVE (Love2D) Game', chunk: 'gaming' },
  sc2replay: { app: 'StarCraft II Replay (MPQ)', chunk: 'gaming' },
  mpq:     { app: 'Blizzard MoPaQ Archive', chunk: 'gaming' },
  cia:     { app: 'Nintendo 3DS CIA', chunk: 'gaming' },
  nsp:     { app: 'Nintendo Switch NSP', chunk: 'gaming' },
  xci:     { app: 'Nintendo Switch XCI', chunk: 'gaming' },
  rpa:     { app: "Ren'Py Archive", chunk: 'gaming' },
  rgssad:  { app: 'RPG Maker Archive', chunk: 'gaming' },
  rgss3a:  { app: 'RPG Maker VX Ace Archive', chunk: 'gaming' },

  // Disk images / filesystems / firmware / virtualization (lazy chunk: parsers-disk.js)
  // DJI firmware (.bin) - reached via the magic route in app.js (sniffedExt 'djifw').
  djifw:   { app: 'DJI Firmware', chunk: 'disk' },
  ovf:     { app: 'OVF Descriptor', chunk: 'disk' },
  ova:     { app: 'OVF Appliance', chunk: 'disk' },
  vbox:    { app: 'VirtualBox Settings', chunk: 'disk' },
  vmx:     { app: 'VMware VM Config', chunk: 'disk' },
  cue:     { app: 'Cue Sheet', chunk: 'disk' },
  ccd:     { app: 'CloneCD Control', chunk: 'disk' },
  nrg:     { app: 'Nero Disc Image', chunk: 'disk' },
  imc:     { app: 'GetDataBack Compressed Image' },   // parsed locally (parseImc)
  mds:     { app: 'Alcohol 120% Descriptor', chunk: 'disk' },
  mdf:     { app: 'Alcohol 120% Media', chunk: 'disk' },
  hex:     { app: 'Intel HEX', chunk: 'disk' },
  srec:    { app: 'Motorola S-record', chunk: 'disk' },
  s19:     { app: 'Motorola S-record', chunk: 'disk' },
  s28:     { app: 'Motorola S-record', chunk: 'disk' },
  s37:     { app: 'Motorola S-record', chunk: 'disk' },
  mot:     { app: 'Motorola S-record', chunk: 'disk' },
  uf2:     { app: 'UF2 Firmware', chunk: 'disk' },
  elf:     { app: 'ELF Executable', chunk: 'disk' },
  axf:     { app: 'ARM ELF Image', chunk: 'disk' },
  o:       { app: 'ELF Object File', chunk: 'disk' },
  so:      { app: 'ELF Shared Object', chunk: 'disk' },
  // .out is either the text a batch job dumped or the a.out an ELF toolchain
  // left behind. This entry covers the text case; the ELF case never reaches it -
  // SNIFF_FIRST in app.js sniffs .out first and routes a real ELF to the `elf`
  // entry above, with its full header parse.
  out:     { app: 'Program output / compiled executable', parse: 'text' },
  dtb:     { app: 'Device Tree Blob', chunk: 'disk' },
  dtbo:    { app: 'Device Tree Overlay', chunk: 'disk' },
  uimage:  { app: 'U-Boot uImage', chunk: 'disk' },
  gpt:     { app: 'GUID Partition Table', chunk: 'disk' },
  mbr:     { app: 'Master Boot Record', chunk: 'disk' },
  ext4:    { app: 'ext4 Filesystem', chunk: 'disk' },
  ext:     { app: 'ext Filesystem', chunk: 'disk' },
  squashfs:{ app: 'SquashFS Image', chunk: 'disk' },
  sfs:     { app: 'SquashFS Image', chunk: 'disk' },
  cramfs:  { app: 'cramfs Image', chunk: 'disk' },
  romfs:   { app: 'romfs Image', chunk: 'disk' },
  wim:     { app: 'Windows Imaging', chunk: 'disk' },
  swm:     { app: 'Split WIM', chunk: 'disk' },
  esd:     { app: 'Windows ESD', chunk: 'disk' },
  ewf:     { app: 'EnCase / EWF Image', chunk: 'disk' },
  jffs2:   { app: 'JFFS2 Firmware', chunk: 'disk' },
  ubifs:   { app: 'UBIFS Firmware', chunk: 'disk' },
  yaffs2:  { app: 'YAFFS2 Image', chunk: 'disk' },
  isz:     { app: 'Compressed ISO', chunk: 'disk' },
  cdi:     { app: 'DiscJuggler Image', chunk: 'disk' },
  vmsn:    { app: 'VMware Snapshot State', chunk: 'disk' },
  vmem:    { app: 'VMware Guest Memory', chunk: 'disk' },
  binwalk: { app: 'Raw Firmware Dump', chunk: 'disk' },

  // Science / medical / engineering (lazy chunk: parsers-sci.js)
  dcm:     { app: 'DICOM Medical Image', chunk: 'sci' },
  dicom:   { app: 'DICOM Medical Image', chunk: 'sci' },
  nii:     { app: 'NIfTI Neuroimaging', chunk: 'sci' },
  fit:     { app: 'Garmin FIT Activity', chunk: 'sci' },
  tcx:     { app: 'Garmin TCX Activity', chunk: 'sci' },
  fits:    { app: 'FITS Astronomy Image', chunk: 'sci' },
  fts:     { app: 'FITS Astronomy Image', chunk: 'sci' },
  fasta:   { app: 'FASTA Sequence', chunk: 'sci' },
  fa:      { app: 'FASTA Sequence', chunk: 'sci' },
  fna:     { app: 'FASTA Sequence', chunk: 'sci' },
  faa:     { app: 'FASTA Sequence', chunk: 'sci' },
  fastq:   { app: 'FASTQ Reads', chunk: 'sci' },
  fq:      { app: 'FASTQ Reads', chunk: 'sci' },
  mol:     { app: 'Molecular Structure', chunk: 'sci' },
  sdf:     { app: 'Molecular Structure (SDF)', chunk: 'sci' },
  mol2:    { app: 'Molecular Structure (MOL2)', chunk: 'sci' },
  cif:     { app: 'Crystallographic CIF', chunk: 'sci' },
  mmcif:   { app: 'Macromolecular CIF', chunk: 'sci' },
  xyz:     { app: 'XYZ Molecular Coordinates', chunk: 'sci' },
  gbr:     { app: 'Gerber PCB', chunk: 'sci' },
  gbl:     { app: 'Gerber PCB', chunk: 'sci' },
  gtl:     { app: 'Gerber PCB', chunk: 'sci' },
  drl:     { app: 'Excellon Drill', chunk: 'sci' },
  xln:     { app: 'Excellon Drill', chunk: 'sci' },
  cir:     { app: 'SPICE Netlist', chunk: 'sci' },
  sp:      { app: 'SPICE Netlist', chunk: 'sci' },
  spi:     { app: 'SPICE Netlist', chunk: 'sci' },
  spice:   { app: 'SPICE Netlist', chunk: 'sci' },
  edf:     { app: 'Biosignal (EDF)', chunk: 'sci' },
  bdf:     { app: 'Biosignal (BDF)', chunk: 'sci' },
  jdx:     { app: 'JCAMP-DX Spectrum', chunk: 'sci' },
  dx:      { app: 'JCAMP-DX Spectrum', chunk: 'sci' },
  sav:     { app: 'SPSS Dataset', chunk: 'sci' },
  dta:     { app: 'Stata Dataset', chunk: 'sci' },
  sas7bdat:{ app: 'SAS Dataset', chunk: 'sci' },
  vtk:     { app: 'VTK / ParaView', chunk: 'sci' },
  vtu:     { app: 'VTK Unstructured', chunk: 'sci' },
  vtp:     { app: 'VTK PolyData', chunk: 'sci' },
  vti:     { app: 'VTK Image', chunk: 'sci' },
  segy:    { app: 'SEG-Y Seismic', chunk: 'sci' },
  sgy:     { app: 'SEG-Y Seismic', chunk: 'sci' },
  bam:     { app: 'Genomics BAM', chunk: 'sci' },
  sam:     { app: 'Genomics SAM', chunk: 'sci' },
  bcf:     { app: 'Genomics BCF', chunk: 'sci' },
  hea:     { app: 'WFDB Header', chunk: 'sci' },

  // OS-specific / system / misc (lazy chunk: parsers-osmisc.js)
  opml:    { app: 'OPML Outline', chunk: 'osmisc' },
  rss:     { app: 'RSS Feed', chunk: 'osmisc' },
  atom:    { app: 'Atom Feed', chunk: 'osmisc' },
  desktop: { app: 'Linux Desktop Entry', chunk: 'osmisc' },
  nfo:     { app: 'NFO / Scene Notes', chunk: 'osmisc' },
  service: { app: 'systemd Unit', chunk: 'osmisc' },
  crash:   { app: 'Apple Crash Report', chunk: 'osmisc' },
  ab:      { app: 'Android Backup', chunk: 'osmisc' },
  job:     { app: 'Task Scheduler Job', chunk: 'osmisc' },
  pol:     { app: 'Group Policy (Registry.pol)', chunk: 'osmisc' },
  scr:     { app: 'Windows Screensaver' },
  ds_store:{ app: 'macOS .DS_Store', chunk: 'osmisc' },
  thumbsdb:{ app: 'Windows Thumbs.db', chunk: 'osmisc' },
  dsym:    { app: 'dSYM Debug Symbols', chunk: 'osmisc' },
  dwarf:   { app: 'DWARF Debug Symbols', chunk: 'osmisc' },
  sdb:     { app: 'Shim Database', chunk: 'osmisc' },

  // Images - decoded/metadata (lazy chunk: parsers-image.js)
  tga:     { app: 'Truevision TGA', chunk: 'image' },
  icb:     { app: 'Truevision TGA', chunk: 'image' },
  vda:     { app: 'Truevision TGA', chunk: 'image' },
  vst:     { app: 'Truevision TGA', chunk: 'image' },
  qoi:     { app: 'QOI Image', chunk: 'image' },
  ppm:     { app: 'Netpbm Pixmap', chunk: 'image' },
  pgm:     { app: 'Netpbm Graymap', chunk: 'image' },
  pbm:     { app: 'Netpbm Bitmap', chunk: 'image' },
  pnm:     { app: 'Netpbm Image', chunk: 'image' },
  pam:     { app: 'Netpbm PAM', chunk: 'image' },
  pcx:     { app: 'PCX (PC Paintbrush)', chunk: 'image' },
  ff:      { app: 'farbfeld Image', chunk: 'image' },
  farbfeld:{ app: 'farbfeld Image', chunk: 'image' },
  wbmp:    { app: 'Wireless Bitmap', chunk: 'image' },
  xbm:     { app: 'X BitMap', chunk: 'image' },
  xpm:     { app: 'X PixMap', chunk: 'image' },
  ras:     { app: 'Sun Raster', chunk: 'image' },
  sun:     { app: 'Sun Raster', chunk: 'image' },
  sgi:     { app: 'SGI / IRIS RGB', chunk: 'image' },
  bw:      { app: 'SGI Grayscale', chunk: 'image' },
  hdr:     { app: 'Radiance HDR', chunk: 'image' },
  dds:     { app: 'DirectDraw Surface', chunk: 'image' },
  exr:     { app: 'OpenEXR', chunk: 'image' },
  jp2:     { app: 'JPEG 2000', chunk: 'image' },
  j2k:     { app: 'JPEG 2000 Codestream', chunk: 'image' },
  jpf:     { app: 'JPEG 2000 (JPX)', chunk: 'image' },
  jpx:     { app: 'JPEG 2000 (JPX)', chunk: 'image' },
  jpc:     { app: 'JPEG 2000 Codestream', chunk: 'image' },
  j2c:     { app: 'JPEG 2000 Codestream', chunk: 'image' },
  jxr:     { app: 'JPEG XR', chunk: 'image' },
  wdp:     { app: 'JPEG XR (HD Photo)', chunk: 'image' },
  hdp:     { app: 'JPEG XR (HD Photo)', chunk: 'image' },
  eps:     { app: 'Encapsulated PostScript', chunk: 'image' },
  epsf:    { app: 'Encapsulated PostScript', chunk: 'image' },
  epsi:    { app: 'Encapsulated PostScript', chunk: 'image' },
  ps:      { app: 'PostScript', chunk: 'image' },
  wmf:     { app: 'Windows Metafile', chunk: 'image' },
  emf:     { app: 'Enhanced Metafile', chunk: 'image' },
  emz:     { app: 'Compressed EMF', chunk: 'image' },
  icns:    { app: 'Apple Icon Image', chunk: 'image' },
  cur:     { app: 'Windows Cursor', chunk: 'image' },
  ani:     { app: 'Animated Cursor', chunk: 'image' },
  mng:     { app: 'MNG Animation', chunk: 'image' },
  lottie:  { app: 'Lottie Animation', chunk: 'image' },
  pict:    { app: 'Apple PICT', chunk: 'image' },
  pct:     { app: 'Apple PICT', chunk: 'image' },
  flif:    { app: 'FLIF Image', chunk: 'image' },
  jbig2:   { app: 'JBIG2 Image', chunk: 'image' },
  jb2:     { app: 'JBIG2 Image', chunk: 'image' },
  jbig:    { app: 'JBIG Image', chunk: 'image' },
  bie:     { app: 'JBIG Codestream', chunk: 'image' },
  cgm:     { app: 'Computer Graphics Metafile', chunk: 'image' },
  cdr:     { app: 'CorelDRAW Drawing', chunk: 'image' },

  // 3D / CAD / point clouds (lazy chunk: parsers-threed.js)
  off:     { app: 'OFF Mesh', chunk: 'threed' },
  vox:     { app: 'MagicaVoxel', chunk: 'threed' },
  dae:     { app: 'COLLADA', chunk: 'threed' },
  zae:     { app: 'COLLADA (Zip)', chunk: 'threed' },
  usdc:    { app: 'USD Crate (Binary)', chunk: 'threed' },
  x3d:     { app: 'X3D', chunk: 'threed' },
  x3dv:    { app: 'X3D (Classic VRML)', chunk: 'threed' },
  wrl:     { app: 'VRML', chunk: 'threed' },
  vrml:    { app: 'VRML', chunk: 'threed' },
  lwo:     { app: 'LightWave Object', chunk: 'threed' },
  lws:     { app: 'LightWave Scene', chunk: 'threed' },
  drawio:  { app: 'draw.io Diagram', chunk: 'threed' },
  dio:     { app: 'draw.io Diagram', chunk: 'threed' },
  md2:     { app: 'Quake II Model', chunk: 'threed' },
  md3:     { app: 'Quake III Model', chunk: 'threed' },
  mdl:     { app: 'Quake / Studiomdl Model', chunk: 'threed' },
  vrm:     { app: 'VRM Avatar', chunk: 'threed' },
  jt:      { app: 'JT (Jupiter Tessellation)', chunk: 'threed' },
  las:     { app: 'LAS Point Cloud', chunk: 'threed' },
  laz:     { app: 'LAZ Point Cloud', chunk: 'threed' },
  pcd:     { app: 'PCD Point Cloud', chunk: 'threed' },
  pts:     { app: 'ASCII Point Cloud', chunk: 'threed' },
  e57:     { app: 'E57 Point Cloud', chunk: 'threed' },
  ifc:     { app: 'IFC (BIM)', chunk: 'threed' },
  ifczip:  { app: 'IFCZIP (BIM)', chunk: 'threed' },
  splat:   { app: 'Gaussian Splat', chunk: 'threed' },
  spz:     { app: 'Compressed Gaussian Splat', chunk: 'threed' },
  abc:     { app: 'Alembic', chunk: 'threed' },
  vdb:     { app: 'OpenVDB', chunk: 'threed' },
  prc:     { app: 'PRC (3D PDF)', chunk: 'threed' },
  fls:     { app: 'FARO Scan', chunk: 'threed' },
  fws:     { app: 'FARO Scan', chunk: 'threed' },

  // Geospatial / GIS (lazy chunk: parsers-geodata.js)
  topojson:{ app: 'TopoJSON', chunk: 'geodata' },
  osm:     { app: 'OpenStreetMap XML', chunk: 'geodata' },
  shx:     { app: 'Shapefile Index', chunk: 'geodata' },
  dbf:     { app: 'dBASE Table', chunk: 'geodata' },
  prj:     { app: 'Projection (WKT)', chunk: 'geodata' },
  cpg:     { app: 'Code Page', chunk: 'geodata' },
  pgw:     { app: 'World File', chunk: 'geodata' },
  tfw:     { app: 'World File', chunk: 'geodata' },
  jgw:     { app: 'World File', chunk: 'geodata' },
  wld:     { app: 'World File', chunk: 'geodata' },
  gml:     { app: 'GML (Geography Markup)', chunk: 'geodata' },
  nmea:    { app: 'NMEA 0183 GPS', chunk: 'geodata' },
  nmea0183:{ app: 'NMEA 0183 GPS', chunk: 'geodata' },
  igc:     { app: 'IGC Flight Log', chunk: 'geodata' },
  tab:     { app: 'MapInfo TAB', chunk: 'geodata' },
  mif:     { app: 'MapInfo Interchange', chunk: 'geodata' },
  vrt:     { app: 'GDAL Virtual Raster', chunk: 'geodata' },
  pmtiles: { app: 'PMTiles', chunk: 'geodata' },
  dt0:     { app: 'DTED Terrain', chunk: 'geodata' },
  dt1:     { app: 'DTED Terrain', chunk: 'geodata' },
  dt2:     { app: 'DTED Terrain', chunk: 'geodata' },
  dted:    { app: 'DTED Terrain', chunk: 'geodata' },
  asc:     { app: 'Esri ASCII Grid', chunk: 'geodata' },
  hgt:     { app: 'SRTM Height', chunk: 'geodata' },
  grib:    { app: 'GRIB Weather', chunk: 'geodata' },
  grb:     { app: 'GRIB Weather', chunk: 'geodata' },
  grib2:   { app: 'GRIB2 Weather', chunk: 'geodata' },
  cdf:     { app: 'NetCDF', chunk: 'geodata' },
  nc4:     { app: 'NetCDF-4', chunk: 'geodata' },
  pbf:     { app: 'OSM PBF', chunk: 'geodata' },
  gpkg:    { app: 'GeoPackage', chunk: 'geodata' },
  mbtiles: { app: 'MBTiles', chunk: 'geodata' },
  sid:     { app: 'MrSID', chunk: 'geodata' },
  ecw:     { app: 'ECW', chunk: 'geodata' },
  gdb:     { app: 'Esri File Geodatabase', chunk: 'geodata' },

  // The Sims / Maxis package (DBPF)
  package: { app: 'The Sims Package (DBPF)', chunk: 'gaming' },

  // Waveform peak / overview sidecar (parsed locally - parsePkf: draws the waveform)
  pkf:     { app: 'DJI Waveform Peak File' },

  // Audio - extra codecs / trackers / chiptune (lazy chunk: parsers-audio.js)
  ape:     { app: "Monkey's Audio", chunk: 'audio' },
  wv:      { app: 'WavPack', chunk: 'audio' },
  tak:     { app: 'TAK Lossless', chunk: 'audio' },
  tta:     { app: 'True Audio', chunk: 'audio' },
  ofr:     { app: 'OptimFROG', chunk: 'audio' },
  ofs:     { app: 'OptimFROG DualStream', chunk: 'audio' },
  shn:     { app: 'Shorten', chunk: 'audio' },
  dsf:     { app: 'DSD Stream File', chunk: 'audio' },
  dff:     { app: 'DSDIFF', chunk: 'audio' },
  mpc:     { app: 'Musepack', chunk: 'audio' },
  'mp+':   { app: 'Musepack', chunk: 'audio' },
  mpp:     { app: 'Musepack', chunk: 'audio' },
  caf:     { app: 'Core Audio Format', chunk: 'audio' },
  rf64:    { app: 'RF64', chunk: 'audio' },
  bw64:    { app: 'BW64', chunk: 'audio' },
  w64:     { app: 'Sony Wave64', chunk: 'audio' },
  au:      { app: 'Sun/NeXT Audio', chunk: 'audio' },
  snd:     { app: 'Sun/NeXT Audio', chunk: 'audio' },
  voc:     { app: 'Creative Voice', chunk: 'audio' },
  bwf:     { app: 'Broadcast Wave', chunk: 'audio' },
  spx:     { app: 'Speex', chunk: 'audio' },
  awb:     { app: 'AMR-WB', chunk: 'audio' },
  qcp:     { app: 'Qualcomm PureVoice', chunk: 'audio' },
  '3ga':   { app: '3GPP Audio', chunk: 'audio' },
  m4r:     { app: 'iPhone Ringtone', chunk: 'audio' },
  gsm:     { app: 'GSM 06.10', chunk: 'audio' },
  mp2:     { app: 'MPEG Layer II', chunk: 'audio' },
  mp1:     { app: 'MPEG Layer I', chunk: 'audio' },
  sf2:     { app: 'SoundFont 2', chunk: 'audio' },
  sf3:     { app: 'SoundFont 3', chunk: 'audio' },
  sfz:     { app: 'SFZ Instrument', chunk: 'audio' },
  dls:     { app: 'Downloadable Sounds', chunk: 'audio' },
  rmi:     { app: 'RIFF MIDI', chunk: 'audio' },
  mmf:     { app: 'SMAF (Yamaha)', chunk: 'audio' },
  gig:     { app: 'GigaStudio', chunk: 'audio' },
  rtttl:   { app: 'RTTTL Ringtone', chunk: 'audio' },
  rtx:     { app: 'RTTTL Ringtone', chunk: 'audio' },
  imy:     { app: 'iMelody', chunk: 'audio' },
  sap:     { app: 'Atari SAP', chunk: 'audio' },
  mod:     { app: 'Amiga Module', chunk: 'audio' },
  xm:      { app: 'Extended Module', chunk: 'audio' },
  it:      { app: 'Impulse Tracker', chunk: 'audio' },
  s3m:     { app: 'Scream Tracker 3', chunk: 'audio' },
  stm:     { app: 'Scream Tracker 2', chunk: 'audio' },
  mtm:     { app: 'MultiTracker', chunk: 'audio' },
  med:     { app: 'OctaMED', chunk: 'audio' },
  mmd:     { app: 'OctaMED', chunk: 'audio' },
  '669':   { app: 'Composer 669', chunk: 'audio' },
  far:     { app: 'Farandole Composer', chunk: 'audio' },
  okt:     { app: 'Oktalyzer', chunk: 'audio' },
  nsf:     { app: 'NES Sound Format', chunk: 'audio' },
  nsfe:    { app: 'NES Sound Format (Extended)', chunk: 'audio' },
  spc:     { app: 'SNES SPC700', chunk: 'audio' },
  vgm:     { app: 'Video Game Music', chunk: 'audio' },
  vgz:     { app: 'Video Game Music', chunk: 'audio' },
  gbs:     { app: 'Game Boy Sound', chunk: 'audio' },
  ay:      { app: 'AY Chiptune', chunk: 'audio' },
  ym:      { app: 'Atari ST YM', chunk: 'audio' },
  aup:     { app: 'Audacity Project', chunk: 'audio' },
  aup3:    { app: 'Audacity 3 Project', chunk: 'audio' },
  mo3:     { app: 'MO3 Compressed Module', chunk: 'audio' },
  umx:     { app: 'Unreal Music Package', chunk: 'audio' },
  psf:     { app: 'Portable Sound Format', chunk: 'audio' },
  minipsf: { app: 'Portable Sound Format', chunk: 'audio' },
  psf2:    { app: 'Portable Sound Format 2', chunk: 'audio' },
  sfark:   { app: 'sfArk SoundFont', chunk: 'audio' },
  mqa:     { app: 'MQA', chunk: 'audio' },

  // Video / streaming (lazy chunk: parsers-video.js)
  m3u8:    { app: 'HLS Playlist', chunk: 'video' },
  m3u:     { app: 'M3U Playlist', chunk: 'video' },
  mpd:     { app: 'MPEG-DASH Manifest', chunk: 'video' },
  ism:     { app: 'Smooth Streaming', chunk: 'video' },
  ismc:    { app: 'Smooth Streaming Manifest', chunk: 'video' },
  f4m:     { app: 'Adobe HDS Manifest', chunk: 'video' },
  asx:     { app: 'WMP Playlist', chunk: 'video' },
  wpl:     { app: 'WMP Playlist', chunk: 'video' },
  xspf:    { app: 'XSPF Playlist', chunk: 'video' },
  pls:     { app: 'PLS Playlist', chunk: 'video' },
  mxf:     { app: 'Material Exchange Format', chunk: 'video' },
  gxf:     { app: 'General Exchange Format', chunk: 'video' },
  lxf:     { app: 'Leitch Exchange Format', chunk: 'video' },
  dv:      { app: 'Raw DV Video', chunk: 'video' },
  dif:     { app: 'Raw DV Video', chunk: 'video' },
  asf:     { app: 'Advanced Systems Format', chunk: 'video' },
  'dvr-ms':{ app: 'Windows Recorded TV', chunk: 'video' },
  rm:      { app: 'RealMedia', chunk: 'video' },
  rmvb:    { app: 'RealMedia VBR', chunk: 'video' },
  divx:    { app: 'DivX Video', chunk: 'video' },
  f4v:     { app: 'Flash MP4 Video', chunk: 'video' },
  insv:    { app: 'Insta360 Video', chunk: 'video' },
  insp:    { app: 'Insta360 Photo', chunk: 'video' },
  lrv:     { app: 'Low-Res Video Proxy', chunk: 'video' },
  gifv:    { app: 'GIFV (Video GIF)', chunk: 'video' },
  ivf:     { app: 'IVF (VPx/AV1)', chunk: 'video' },
  y4m:     { app: 'YUV4MPEG2', chunk: 'video' },
  m2v:     { app: 'MPEG-2 Video', chunk: 'video' },
  m1v:     { app: 'MPEG-1 Video', chunk: 'video' },
  mpv:     { app: 'MPEG Video', chunk: 'video' },
  '264':   { app: 'Raw H.264 Stream', chunk: 'video' },
  h264:    { app: 'Raw H.264 Stream', chunk: 'video' },
  avc:     { app: 'Raw H.264 / AVC', chunk: 'video' },
  '265':   { app: 'Raw H.265 Stream', chunk: 'video' },
  h265:    { app: 'Raw H.265 Stream', chunk: 'video' },
  hevc:    { app: 'Raw HEVC Stream', chunk: 'video' },
  obu:     { app: 'AV1 OBU Stream', chunk: 'video' },
  m2p:     { app: 'MPEG-2 Program Stream', chunk: 'video' },
  h2v:     { app: 'MPEG-2 Stream', chunk: 'video' },
  m2t:     { app: 'MPEG-2 Transport', chunk: 'video' },
  trp:     { app: 'PVR/DVB Recording', chunk: 'video' },
  tp:      { app: 'PVR/DVB Recording', chunk: 'video' },
  wtv:     { app: 'Windows Recorded TV', chunk: 'video' },
  ogm:     { app: 'Ogg Media', chunk: 'video' },
  nut:     { app: 'NUT Container', chunk: 'video' },
  dpx:     { app: 'Digital Picture Exchange', chunk: 'video' },
  cin:     { app: 'Cineon', chunk: 'video' },
  dav:     { app: 'Dahua DVR Video', chunk: 'video' },
  yuv:     { app: 'Raw YUV', chunk: 'video' },

  // Documents / ebooks / publishing (lazy chunk: parsers-docs.js)
  cbz:     { app: 'Comic Book ZIP', chunk: 'docs' },
  cbt:     { app: 'Comic Book TAR', chunk: 'docs' },
  xps:     { app: 'XPS Document', chunk: 'docs' },
  oxps:    { app: 'OpenXPS Document', chunk: 'docs' },
  hwpx:    { app: 'Hangul HWPX', chunk: 'docs' },
  fb3:     { app: 'FictionBook 3', chunk: 'docs' },
  ibooks:  { app: 'iBooks Author', chunk: 'docs' },
  scriv:   { app: 'Scrivener Project', chunk: 'docs' },
  scrivx:  { app: 'Scrivener Index', chunk: 'docs' },
  abw:     { app: 'AbiWord Document', chunk: 'docs' },
  zabw:    { app: 'AbiWord (gzip)', chunk: 'docs' },
  sxw:     { app: 'StarOffice Writer', chunk: 'docs' },
  sxc:     { app: 'StarOffice Calc', chunk: 'docs' },
  sxi:     { app: 'StarOffice Impress', chunk: 'docs' },
  fodt:    { app: 'ODF Flat Text', chunk: 'docs' },
  fods:    { app: 'ODF Flat Spreadsheet', chunk: 'docs' },
  fodp:    { app: 'ODF Flat Slides', chunk: 'docs' },
  fodg:    { app: 'ODF Flat Graphics', chunk: 'docs' },
  ott:     { app: 'ODF Text Template', chunk: 'docs' },
  ots:     { app: 'ODF Sheet Template', chunk: 'docs' },
  otp:     { app: 'ODF Slides Template', chunk: 'docs' },
  dotx:    { app: 'Word Template', chunk: 'docs' },
  dotm:    { app: 'Word Macro Template', chunk: 'docs' },
  vsdx:    { app: 'Visio Drawing', chunk: 'docs' },
  tex:     { app: 'TeX / LaTeX Source', chunk: 'docs' },
  latex:   { app: 'LaTeX Source', chunk: 'docs' },
  sty:     { app: 'LaTeX Style', chunk: 'docs' },
  cls:     { app: 'LaTeX Class', chunk: 'docs' },
  bib:     { app: 'BibTeX Bibliography', chunk: 'docs' },
  rst:     { app: 'reStructuredText', chunk: 'docs' },
  adoc:    { app: 'AsciiDoc', chunk: 'docs' },
  asciidoc:{ app: 'AsciiDoc', chunk: 'docs' },
  org:     { app: 'Emacs Org-mode', chunk: 'docs' },
  textile: { app: 'Textile Markup', chunk: 'docs' },
  tei:     { app: 'TEI XML', chunk: 'docs' },
  rmd:     { app: 'R Markdown', chunk: 'docs' },
  qmd:     { app: 'Quarto Document', chunk: 'docs' },
  rtfd:    { app: 'Rich Text Directory', chunk: 'docs' },
  mht:     { app: 'MHTML Web Archive', chunk: 'docs' },
  mhtml:   { app: 'MHTML Web Archive', chunk: 'docs' },
  warc:    { app: 'Web ARChive', chunk: 'docs' },
  maff:    { app: 'Mozilla Archive', chunk: 'docs' },
  jats:    { app: 'JATS Journal XML', chunk: 'docs' },
  nxml:    { app: 'JATS (NXML)', chunk: 'docs' },
  dvi:     { app: 'TeX DVI', chunk: 'docs' },
  cbr:     { app: 'Comic Book RAR', chunk: 'docs' },
  cb7:     { app: 'Comic Book 7-Zip', chunk: 'docs' },
  chm:     { app: 'Compiled HTML Help', chunk: 'docs' },
  wpd:     { app: 'WordPerfect Document', chunk: 'docs' },
  hwp:     { app: 'Hangul HWP', chunk: 'docs' },
  qxd:     { app: 'QuarkXPress', chunk: 'docs' },
  qxp:     { app: 'QuarkXPress', chunk: 'docs' },
  pmd:     { app: 'PageMaker', chunk: 'docs' },
  lit:     { app: 'MS Reader e-book', chunk: 'docs' },
  kfx:     { app: 'Amazon KFX', chunk: 'docs' },

  // Camera RAW edit sidecars (lazy chunk: parsers-raw.js)
  aae:     { app: 'Apple Photos Adjustments', chunk: 'raw' },
  pp3:     { app: 'RawTherapee Profile', chunk: 'raw' },
  cos:     { app: 'Capture One Settings', chunk: 'raw' },
  cof:     { app: 'Capture One Sidecar', chunk: 'raw' },
  cop:     { app: 'Capture One Preview', chunk: 'raw' },
  comask:  { app: 'Capture One Mask', chunk: 'raw' },
  dop:     { app: 'DxO PhotoLab Sidecar', chunk: 'raw' },
  nksc:    { app: 'Nikon NX Studio Sidecar', chunk: 'raw' },

  // Cinema RAW & rare camera RAW (identification-only - no in-browser decoder)
  r3d:     { app: 'REDCODE RAW' },
  braw:    { app: 'Blackmagic RAW' },
  crm:     { app: 'Canon Cinema RAW Light' },
  ari:     { app: 'ARRIRAW' },
  arx:     { app: 'ARRIRAW' },
  cine:    { app: 'Phantom CINE' },
  fpf:     { app: 'FLIR Public Image' },
  eip:     { app: 'Capture One EIP', zip: true },
  bay:     { app: 'Casio Bayer RAW' },
  pxn:     { app: 'Logitech Fotoman RAW' },
  rwz:     { app: 'Rawzor Compressed RAW' },

  // Adobe After Effects XML project
  aepx:    { app: 'Adobe After Effects (XML)', parse: 'xml' },

  // Rich Text
  rtf:     { app: 'Rich Text Format', parse: 'text' },

  // X.509 certificates / keys
  crt:     { app: 'X.509 Certificate' },
  cer:     { app: 'X.509 Certificate' },
  pem:     { app: 'PEM Certificate / Key' },
  der:     { app: 'DER Certificate' },

  // Partial downloads
  part:    { app: 'Partial Download' },
  crdownload: { app: 'Chrome Partial Download' },

  // Dolby surround / object audio containers
  ec3:     { app: 'Dolby Digital Plus (E-AC-3)' },
  eac3:    { app: 'Dolby Digital Plus (E-AC-3)' },
  thd:     { app: 'Dolby TrueHD' },
  mlp:     { app: 'Meridian Lossless Packing' },
  atmos:   { app: 'Dolby Atmos Master' },

  // Engineering
  cdp:     { app: 'CDP4 (COMET) / Criterium DecisionPlus' },

  // Game saves
  bepis:   { app: 'ULTRAKILL Save' },

  // Valve / Steam
  vdf:     { app: 'Valve Data (KeyValues)' },
  acf:     { app: 'Steam App Manifest' },

  // Camera catalog (the DCIM index a Canon camera writes alongside the photos)
  ctg:     { app: 'Canon Camera Catalog' },

  // Shortcuts
  lnk:     { app: 'Windows Shortcut' },
  url:     { app: 'Internet Shortcut', parse: 'text' },
  webloc:  { app: 'macOS Web Shortcut', parse: 'xml' },

  // REC: ambiguous - a PVR/DVR video recording OR a data-recovery session.
  // parseRec() sniffs the content to tell which.
  rec:     { app: 'REC File' },

  // ===== Developer / data / serialization (parsers-dev.js) =====
  lock:    { app: 'Dependency Lockfile', chunk: 'dev', parse: 'text' },
  json5:   { app: 'JSON5', chunk: 'dev', parse: 'text' },
  jsonc:   { app: 'JSON with Comments', chunk: 'dev', parse: 'text' },
  hjson:   { app: 'Hjson', chunk: 'dev', parse: 'text' },
  pb:      { app: 'Protobuf Message', chunk: 'dev' },
  msgpack: { app: 'MessagePack', chunk: 'dev' },
  mpk:     { app: 'MessagePack', chunk: 'dev' },
  bson:    { app: 'BSON (MongoDB)', chunk: 'dev' },
  cbor:    { app: 'CBOR', chunk: 'dev' },
  pkl:     { app: 'Python Pickle', chunk: 'dev' },
  pickle:  { app: 'Python Pickle', chunk: 'dev' },
  npz:     { app: 'NumPy Zipped Arrays', chunk: 'dev', zip: true },
  jar:     { app: 'Java Archive', chunk: 'dev', zip: true },
  war:     { app: 'Java Web Archive', chunk: 'dev', zip: true },
  ear:     { app: 'Java Enterprise Archive', chunk: 'dev', zip: true },
  fbs:     { app: 'FlatBuffers Schema', chunk: 'dev', parse: 'text' },
  thrift:  { app: 'Apache Thrift IDL', chunk: 'dev', parse: 'text' },
  capnp:   { app: "Cap'n Proto Schema", chunk: 'dev', parse: 'text' },
  hcl:     { app: 'HashiCorp HCL', chunk: 'dev', parse: 'text' },
  mat:     { app: 'MATLAB MAT-file', chunk: 'dev' },
  rdb:     { app: 'Redis RDB Dump', chunk: 'dev' },
  arrow:   { app: 'Apache Arrow IPC', chunk: 'dev' },
  feather: { app: 'Apache Arrow Feather', chunk: 'dev' },
  parquet: { app: 'Apache Parquet', chunk: 'dev' },
  orc:     { app: 'Apache ORC', chunk: 'dev' },
  desc:    { app: 'Protobuf Descriptor Set', chunk: 'dev' },
  dump:    { app: 'SQL Dump', chunk: 'dev' },

  // ===== Archives / packages / installers (parsers-archive.js) =====
  jnlp:    { app: 'Java Web Start (JNLP)', parse: 'xml' },
  msu:     { app: 'Windows Update Standalone', chunk: 'archive' },
  xar:     { app: 'XAR Archive', chunk: 'archive' },
  pkg:     { app: 'macOS Installer Package', chunk: 'archive' },
  mpkg:    { app: 'macOS Meta Installer', chunk: 'archive' },
  snap:    { app: 'Snap Package (SquashFS)', chunk: 'archive' },
  flatpak: { app: 'Flatpak Bundle', chunk: 'archive' },
  sit:     { app: 'StuffIt Archive', chunk: 'archive' },
  sitx:    { app: 'StuffIt X Archive', chunk: 'archive' },
  lzo:     { app: 'lzop Compressed', chunk: 'archive' },
  br:      { app: 'Brotli Stream', chunk: 'archive' },
  tlz:     { app: 'LZMA/XZ Tarball', chunk: 'archive' },
  tbz:     { app: 'Bzip2 Tarball', chunk: 'archive' },
  tz:      { app: 'compress Tarball', chunk: 'archive' },

  // ===== 3D / CAD / mesh / scene (parsers-threed.js) =====
  drc:     { app: 'Draco Compressed Mesh', chunk: 'threed' },
  ksplat:  { app: 'Block-Compressed Splat', chunk: 'threed' },
  u3d:     { app: 'Universal 3D', chunk: 'threed' },
  '3dxml': { app: '3DXML (Dassault)', zip: true, chunk: 'threed' },
  x:       { app: 'DirectX Model', chunk: 'threed' },
  qb:      { app: 'Qubicle Binary', chunk: 'threed' },
  wings:   { app: 'Wings3D Model', chunk: 'threed' },
  pln:     { app: 'Graphisoft ArchiCAD Project', chunk: 'threed' },
  pla:     { app: 'Graphisoft ArchiCAD Archive', chunk: 'threed' },
  rvt:     { app: 'Autodesk Revit Project', chunk: 'threed' },
  rfa:     { app: 'Autodesk Revit Family', chunk: 'threed' },
  rte:     { app: 'Revit Project Template', chunk: 'threed' },
  rft:     { app: 'Revit Family Template', chunk: 'threed' },
  par:     { app: 'Solid Edge Part', chunk: 'threed' },
  psm:     { app: 'Solid Edge Sheet Metal', chunk: 'threed' },
  pwd:     { app: 'Solid Edge Weldment', chunk: 'threed' },
  nwd:     { app: 'Navisworks Published', chunk: 'threed' },
  nwf:     { app: 'Navisworks File Set', chunk: 'threed' },
  nwc:     { app: 'Navisworks Cache', chunk: 'threed' },
  model:   { app: 'CATIA V4 Model', chunk: 'threed' },
  exp:     { app: 'CATIA V4 Export', chunk: 'threed' },
  dlv:     { app: 'CATIA V4 Result', chunk: 'threed' },
  session: { app: 'CATIA V4 Session', chunk: 'threed' },
  cl3:     { app: 'FARO Scan (CL3)', chunk: 'threed' },
  clr:     { app: 'FARO Scan (CLR)', chunk: 'threed' },
  tzf:     { app: 'Trimble Scan (TZF)', chunk: 'threed' },
  vsd:     { app: 'Visio Drawing (Binary)', chunk: 'threed' },

  // ===== Disk images / filesystems / firmware / VM (parsers-disk.js) =====
  trx:     { app: 'TRX Firmware', chunk: 'disk' },
  dfu:     { app: 'USB DFU Firmware', chunk: 'disk' },
  fd:      { app: 'UEFI / BIOS Firmware', chunk: 'disk' },
  rom:     { app: 'UEFI / BIOS / ROM Image', chunk: 'disk' },
  ubi:     { app: 'UBI Volume', chunk: 'disk' },
  simg:    { app: 'Android Sparse Image', chunk: 'disk' },
  itb:     { app: 'Flattened Image Tree', chunk: 'disk' },
  dsk:     { app: 'Raw Floppy / Disk Image', chunk: 'disk' },
  ima:     { app: 'Raw Floppy Image', chunk: 'disk' },
  vfd:     { app: 'Virtual Floppy Disk', chunk: 'disk' },
  vmsd:    { app: 'VMware Snapshot Metadata', chunk: 'disk' },
  nvram:   { app: 'VMware NVRAM', chunk: 'disk' },
  pvm:     { app: 'Parallels VM Bundle', chunk: 'disk' },
  hdd:     { app: 'Parallels / Virtual PC Disk', chunk: 'disk' },
  mf:      { app: 'OVF Manifest', chunk: 'disk' },
  vbk:     { app: 'Veeam Backup', chunk: 'disk' },

  // ===== Gaming / emulation / console / game assets (parsers-gaming.js) =====
  assets:   { app: 'Unity Asset Bundle', chunk: 'gaming' },
  bundle:   { app: 'Unity Asset Bundle', chunk: 'gaming' },
  resource: { app: 'Unity Asset Bundle', chunk: 'gaming' },
  utoc:     { app: 'Unreal IO Store TOC', chunk: 'gaming' },
  ucas:     { app: 'Unreal IO Store Data', chunk: 'gaming' },
  uexp:     { app: 'Unreal Cooked Export', chunk: 'gaming' },
  umd:      { app: 'Unreal Cooked Asset', chunk: 'gaming' },
  cso:      { app: 'Compressed ISO (CISO)', chunk: 'gaming' },
  chd:      { app: 'MAME Compressed Image', chunk: 'gaming' },
  fsb:      { app: 'FMOD Sound Bank', chunk: 'gaming' },
  bank:     { app: 'FMOD Studio Bank', chunk: 'gaming' },
  bnk:      { app: 'Wwise Sound Bank', chunk: 'gaming' },
  wem:      { app: 'Wwise Audio', chunk: 'gaming' },
  spine:    { app: 'Spine Skeleton', chunk: 'gaming' },
  skel:     { app: 'Spine Skeleton (binary)', chunk: 'gaming' },
  atlas:    { app: 'Spine / Sprite Atlas', chunk: 'gaming' },
  yyp:      { app: 'GameMaker Project', chunk: 'gaming' },
  yy:       { app: 'GameMaker Resource', chunk: 'gaming' },
  gmx:      { app: 'GameMaker (legacy) Resource', chunk: 'gaming' },
  mca:      { app: 'Minecraft Region (Anvil)', chunk: 'gaming' },
  mcr:      { app: 'Minecraft Region (legacy)', chunk: 'gaming' },
  mctemplate: { app: 'Minecraft Bedrock Template', chunk: 'gaming' },
  '3dsx':   { app: '3DS Homebrew', chunk: 'gaming' },
  a78:      { app: 'Atari 7800 ROM', chunk: 'gaming' },
  a26:      { app: 'Atari 2600 ROM', chunk: 'gaming' },
  lnx:      { app: 'Atari Lynx ROM', chunk: 'gaming' },
  j64:      { app: 'Atari Jaguar ROM', chunk: 'gaming' },
  pce:      { app: 'PC Engine ROM', chunk: 'gaming' },
  gg:       { app: 'Sega Game Gear ROM', chunk: 'gaming' },
  sms:      { app: 'Sega Master System ROM', chunk: 'gaming' },
  ws:       { app: 'WonderSwan ROM', chunk: 'gaming' },
  wsc:      { app: 'WonderSwan Color ROM', chunk: 'gaming' },
  w3x:      { app: 'Warcraft III Map', chunk: 'gaming' },
  w3m:      { app: 'Warcraft III Map', chunk: 'gaming' },
  rpyc:     { app: "Ren'Py Compiled Script", chunk: 'gaming' },
  rvdata2:  { app: 'RPG Maker VX Ace Data', chunk: 'gaming' },
  rxdata:   { app: 'RPG Maker XP Data', chunk: 'gaming' },
  pyxel:    { app: 'Pyxel Edit Document', chunk: 'gaming' },
  ldtk:     { app: 'LDtk Level Project', chunk: 'gaming' },
  tic:      { app: 'TIC-80 Cartridge', chunk: 'gaming' },
  xdelta:   { app: 'xdelta3 Patch (VCDIFF)', chunk: 'gaming' },
  basis:    { app: 'Basis Universal Texture', chunk: 'gaming' },
  srm:      { app: 'Emulator Battery Save', chunk: 'gaming' },
  state:    { app: 'Emulator Save State', chunk: 'gaming' },
  dsv:      { app: 'DeSmuME Save', chunk: 'gaming' },
  dsm:      { app: 'DeSmuME Movie', chunk: 'gaming' },
  vbm:      { app: 'VBA Movie', chunk: 'gaming' },
  fm2:      { app: 'FCEUX Movie', chunk: 'gaming' },

  // ===== Documents / ebooks / publishing (parsers-docs.js) =====
  dita:    { app: 'DITA Topic', parse: 'xml', chunk: 'docs' },
  ditamap: { app: 'DITA Map', parse: 'xml', chunk: 'docs' },
  sla:     { app: 'Scribus Document', chunk: 'docs' },
  scd:     { app: 'Scribus Legacy', chunk: 'docs' },
  wps:     { app: 'MS Works WP', chunk: 'docs' },
  wpt:     { app: 'MS Works Template', chunk: 'docs' },
  wri:     { app: 'Windows Write', chunk: 'docs' },
  dot:     { app: 'Word 97 Template', chunk: 'docs' },
  sdw:     { app: 'StarOffice Writer 5', chunk: 'docs' },
  sdc:     { app: 'StarOffice Calc 5', chunk: 'docs' },
  sdd:     { app: 'StarOffice Impress 5', chunk: 'docs' },
  snb:     { app: 'Shanda Bambook e-book', chunk: 'docs' },
  lrf:     { app: 'Sony BBeB Book', chunk: 'docs' },
  lrx:     { app: 'Sony BBeB (DRM)', chunk: 'docs' },
  tcr:     { app: 'Psion / EBookwise TCR', chunk: 'docs' },
  cba:     { app: 'Comic Book ACE', chunk: 'docs' },
  fm:      { app: 'FrameMaker Document', chunk: 'docs' },
  book:    { app: 'FrameMaker Book', chunk: 'docs' },
  awt:     { app: 'AbiWord Template', chunk: 'docs' },
  sxd:     { app: 'StarOffice Draw', zip: true, chunk: 'docs' },
  otg:     { app: 'ODF Graphics Template', zip: true, chunk: 'docs' },
  pm6:     { app: 'PageMaker 6', chunk: 'docs' },
  p65:     { app: 'PageMaker 6.5', chunk: 'docs' },
  pt6:     { app: 'PageMaker Template', chunk: 'docs' },
  adf:     { app: 'AsciiDoc', parse: 'text', chunk: 'docs' },

  // ===== Email / calendar / contacts / PIM (parsers-email.js) =====
  olm:     { app: 'Outlook for Mac Archive', zip: true, chunk: 'email' },
  oft:     { app: 'Outlook Template', chunk: 'email' },
  p7m:     { app: 'S/MIME Encrypted Message', chunk: 'email' },
  p7s:     { app: 'S/MIME Signature', chunk: 'email' },
  msf:     { app: 'Mozilla Mail Summary', chunk: 'email' },
  mab:     { app: 'Mozilla Address Book', chunk: 'email' },
  mbx:     { app: 'Eudora / OE Mailbox', chunk: 'email' },
  toc:     { app: 'Eudora Table of Contents', chunk: 'email' },
  vmg:     { app: 'vMessage SMS Backup', parse: 'text', chunk: 'email' },
  vnt:     { app: 'vNote', parse: 'text', chunk: 'email' },
  xcal:    { app: 'iCalendar (XML)', parse: 'xml', chunk: 'email' },
  jcal:    { app: 'iCalendar (JSON)', chunk: 'email' },
  xcard:   { app: 'vCard (XML)', parse: 'xml', chunk: 'email' },
  jcard:   { app: 'vCard (JSON)', chunk: 'email' },
  ldi:     { app: 'LDIF (LDAP Export)', parse: 'text', chunk: 'email' },
  pab:     { app: 'Personal Address Book', chunk: 'email' },
  wab:     { app: 'Windows Address Book', chunk: 'email' },
  abbu:    { app: 'Apple Address Book Backup', chunk: 'email' },

  // ===== Security / crypto / keys / forensics (parsers-security.js) =====
  pgp:     { app: 'OpenPGP Data', chunk: 'security' },
  gpg:     { app: 'OpenPGP Data', chunk: 'security' },
  sig:     { app: 'OpenPGP Signature', chunk: 'security' },
  evt:     { app: 'Windows Event Log (legacy)', chunk: 'security' },
  yar:     { app: 'YARA Rules', parse: 'text', chunk: 'security' },
  yara:    { app: 'YARA Rules', parse: 'text', chunk: 'security' },
  rules:   { app: 'Snort / Suricata IDS Rules', parse: 'text', chunk: 'security' },
  stix:    { app: 'STIX Threat Intel', parse: 'text', chunk: 'security' },
  ioc:     { app: 'OpenIOC Indicator', parse: 'xml', chunk: 'security' },
  saz:     { app: 'Fiddler Session Archive', zip: true, chunk: 'security' },
  '1pux':  { app: '1Password Export', zip: true, chunk: 'security' },
  opvault: { app: '1Password OPVault', chunk: 'security' },
  keychain:{ app: 'Apple Keychain', chunk: 'security' },
  aff:     { app: 'AFF Forensic Image', chunk: 'security' },
  aff4:    { app: 'AFF4 Forensic Image', zip: true, chunk: 'security' },
  kdb:     { app: 'KeePass 1.x Database', chunk: 'security' },
  pvk:     { app: 'Microsoft Private Key', chunk: 'security' },

  // ===== Scientific / medical / engineering / simulation (parsers-sci.js) =====
  rds:     { app: 'R Serialized Object', chunk: 'sci' },
  rdata:   { app: 'R Workspace', chunk: 'sci' },
  rda:     { app: 'R Workspace', chunk: 'sci' },
  ab1:     { app: 'ABIF Sequencing Trace', chunk: 'sci' },
  poscar:  { app: 'VASP POSCAR (DFT)', parse: 'text', chunk: 'sci' },
  cube:    { app: 'Gaussian Cube', parse: 'text', chunk: 'sci' },
  xsf:     { app: 'XCrySDen Structure', parse: 'text', chunk: 'sci' },
  cdx:     { app: 'ChemDraw Binary', chunk: 'sci' },
  cdxml:   { app: 'ChemDraw XML', parse: 'xml', chunk: 'sci' },
  abf:     { app: 'Axon Binary File', chunk: 'sci' },
  tdms:    { app: 'NI TDMS', chunk: 'sci' },
  vhdr:    { app: 'BrainVision Header', parse: 'text', chunk: 'sci' },
  vmrk:    { app: 'BrainVision Markers', parse: 'text', chunk: 'sci' },
  cnt:     { app: 'Neuroscan EEG', chunk: 'sci' },
  eeg:     { app: 'EEG Data', chunk: 'sci' },
  set:     { app: 'EEGLAB Dataset', chunk: 'sci' },
  vts:     { app: 'VTK Structured Grid', parse: 'xml', chunk: 'sci' },
  vtr:     { app: 'VTK Rectilinear Grid', parse: 'xml', chunk: 'sci' },
  net:     { app: 'SPICE Netlist', parse: 'text', chunk: 'sci' },
  msh:     { app: 'Gmsh Mesh', parse: 'text', chunk: 'sci' },
  inp:     { app: 'Abaqus / Nastran Deck', parse: 'text', chunk: 'sci' },
  cdb:     { app: 'ANSYS CDB Archive', parse: 'text', chunk: 'sci' },
  wfm:     { app: 'Oscilloscope Waveform', chunk: 'sci' },

  // ===== Geospatial / GIS / remote sensing (parsers-geodata.js) =====
  o5m:     { app: 'OSM o5m binary', chunk: 'geodata' },
  o5c:     { app: 'OSM o5c change', chunk: 'geodata' },
  lyr:     { app: 'Esri Layer (ArcMap)', chunk: 'geodata' },
  lyrx:    { app: 'Esri ArcGIS Pro Layer', parse: 'text', chunk: 'geodata' },
  qgs:     { app: 'QGIS Project (XML)', parse: 'xml', chunk: 'geodata' },
  qgz:     { app: 'QGIS Project (ZIP)', zip: true, chunk: 'geodata' },
  sbn:     { app: 'Shapefile Spatial Index', chunk: 'geodata' },
  sbx:     { app: 'Shapefile Spatial Index', chunk: 'geodata' },
  cpt:     { app: 'Colour Palette (GMT/GDAL)', parse: 'text', chunk: 'geodata' },
  bil:     { app: 'Band-Interleaved Raster', chunk: 'geodata' },
  bip:     { app: 'Band-Interleaved Raster', chunk: 'geodata' },
  bsq:     { app: 'Band-Sequential Raster', chunk: 'geodata' },
};
