/* Stamp the shared <head> tail - the two stylesheet links plus the before-first-
   paint theme bootstrap script - into every main page from one source.
   ============================================================================
   WHY: that tail is byte-identical on every page, and the theme <script> in
   particular was hand-copied across all 6 pages AND a 7th time inside
   prerender-format-pages.mjs. A UX/security-sensitive snippet duplicated 7+ ways
   is a change-it-in-7-places hazard. The script now lives once, as THEME_SCRIPT
   in tools/prerender-common.mjs; this script stamps it (with the stylesheet
   links) into the hand pages, and the generator imports the same const.

   HOW: each page wraps its head tail in HEAD:START / HEAD:END markers; this
   rewrites only what sits between them. Everything else in <head> - the per-page
   title/description/canonical/OG/JSON-LD - is left untouched. Mirrors
   tools/stamp-footer.mjs exactly. Re-runnable and idempotent.

   RUN: `node tools/stamp-head.mjs` (save.bat runs it on every commit, before
   `git add`).
   ============================================================================ */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { THEME_SCRIPT } from './prerender-common.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Same "main pages only" scope as stamp-footer; the per-format /formats/<ext>
// pages get THEME_SCRIPT directly from prerender-format-pages.mjs instead.
const PAGES = ['index.html', 'about.html', 'patch.html', 'stats.html', 'privacy.html', 'formats.html', 'samples.html'];

const START = '<!-- HEAD:START - generated by tools/stamp-head.mjs from tools/prerender-common.mjs THEME_SCRIPT; do not hand-edit between the markers -->';
const END = '<!-- HEAD:END -->';
const RE = /<!--\s*HEAD:START[\s\S]*?HEAD:END\s*-->/;
const block = `${START}\n  <link rel="stylesheet" href="assets/css/fonts.css">\n  <link rel="stylesheet" href="assets/css/analyser.css">\n  ${THEME_SCRIPT}\n  ${END}`;

let changed = 0;
const missing = [];
for (const name of PAGES) {
  const file = join(ROOT, name);
  const html = readFileSync(file, 'utf8');
  if (!RE.test(html)) { missing.push(name); continue; }
  // Function replacer so $-sequences in the block are never interpreted.
  const next = html.replace(RE, () => block);
  if (next !== html) { writeFileSync(file, next); changed++; }
}

if (missing.length) {
  console.warn('stamp-head: HEAD markers not found in: ' + missing.join(', ') +
    ' - add <!-- HEAD:START --> ... <!-- HEAD:END --> around the stylesheet links + theme script at the end of <head>.');
}
console.log(`stamp-head: stamped ${changed}/${PAGES.length} page(s) from prerender-common THEME_SCRIPT`);
