/* Stamp the live format count (and sitemap lastmod) into the STATIC, crawler-only
   surfaces that can't run JS.
   ============================================================================
   WHY: the in-app "{n}+ formats" affordances are filled at runtime from
   formatCount() (see the data-fmt-count pass in app.js), but the SEO copy a
   crawler actually reads - the meta/OG/Twitter descriptions, the WebApplication
   JSON-LD featureList, the static feature-spec text, the PWA manifest - is plain
   text with no JS. Hand-maintained "200+ / 740+" numbers drifted apart from the
   real catalog size. This bakes the single source of truth (formatCount()) into
   all of them so the numbers can never disagree again.

   It also stamps the main sitemap.xml <lastmod> dates to the build date, so the
   three hand-listed URLs don't advertise a frozen 2026-06-07.

   The genuinely-narrower "200+ proprietary formats identified by magic bytes"
   claim (llms.txt / README) is a different, smaller metric and is left alone.

   It also writes worker/supported-exts.js: the set of extensions the catalog
   recognises, which the stats Worker imports to decide `supported` SERVER-side
   (a client-sent flag can't be trusted - one POST could otherwise put any string
   on the public /stats page). It lives here rather than as its own save.bat step
   because it is derived from the same catalog import and must track it on every
   commit exactly like the counts do.

   RUN: `node tools/stamp-counts.mjs` (save.bat runs it on every commit, before
   `git add`, so the static numbers track the catalog automatically).
   ============================================================================ */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const WEB = join(ROOT, 'web');   // the website source; tools/ + worker/ stay under ROOT

const fmts = await import(
  pathToFileURL(join(WEB, 'assets/js/core/formats.js')).href
);
const { formatCount } = fmts;
const n = formatCount();

// --- worker/supported-exts.js ------------------------------------------------
// Every extension Analyser recognises, normalised the way the Worker stores an
// ext_stats key (cleanExt in worker/index.js: lowercase, a-z0-9 only, <= 16
// chars). Two sources: the classification *_EXTS sets that route a drop to a real
// renderer, and every catalog row's exts (full analysis + identification) - the
// surface the site advertises as supported. tools/disperse-unsupported.mjs reads
// the generated file too, so the two can never disagree.
function workerExt(raw) {
  const e = String(raw || '').toLowerCase().replace(/[^a-z0-9]/g, '');
  return (!e || e.length > 16) ? null : e;
}
const supportedExts = new Set();
const addExt = (tok) => { const c = workerExt(tok); if (c) supportedExts.add(c); };
for (const key of ['PHOTO_EXTS', 'AUDIO_EXTS', 'VIDEO_EXTS', 'CSV_EXTS', 'SVG_EXTS',
  'HEIC_EXTS', 'RAW_EXTS', 'DOC_EXTS', 'ARCHIVE_EXTS']) {
  const set = fmts[key];
  if (set) for (const e of set) addExt(e);
}
for (const row of [...fmts.FULL_ANALYSIS, ...fmts.IDENTIFICATION]) {
  for (const tok of String(row.exts || '').split(/\s+/)) addExt(tok);
}
{
  const list = [...supportedExts].sort();
  const lines = [];
  for (let i = 0; i < list.length; i += 12) lines.push('  ' + list.slice(i, i + 12).map((e) => `'${e}'`).join(', ') + ',');
  const body = '// Generated by tools/stamp-counts.mjs from the formats catalog - do not hand-edit.\n'
    + '// The extensions the stats Worker (worker/index.js) lists individually on /stats;\n'
    + '// anything else is pooled into "(unsupported)" and never shown by name.\n'
    + `// ${list.length} extensions.\n`
    + 'export const SUPPORTED_EXTS = new Set([\n' + lines.join('\n') + '\n]);\n';
  const out = join(ROOT, 'worker', 'supported-exts.js');
  let prev = null;
  try { prev = readFileSync(out, 'utf8'); } catch (_) { /* first run */ }
  if (prev !== body) {
    writeFileSync(out, body);
    console.log(`stamp-counts: updated worker/supported-exts.js (${list.length} extensions)`);
  }
}

// today, YYYY-MM-DD (local). A regular node script, so new Date() is fine here.
const d = new Date();
const today = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

// Reusable [regex, replacement] passes. Each uses the live count and is written so
// re-running is idempotent (it matches whatever number is currently there).
const fmtTypes = [/\d+\+ file types/g, `${n}+ file types`];
const fmtFormats = [/\d+\+ file formats/g, `${n}+ file formats`];
const fmtFormatsAngle = [/(>)\d+\+ formats(<)/g, `$1${n}+ formats$2`];
// Static fallbacks app.js overwrites at runtime (data-fmt-count); bake them so a
// no-JS crawler / social card never sees a stale number.
const bareCount = [/(data-fmt-count="bare">)\d+/g, `$1${n}`];
const browseAll = [/Browse all \d+ supported formats/g, `Browse all ${n} supported formats`];

// One file, a list of passes. The shared footer's "File ID ... NNN+ file formats"
// line lives in tools/partials/footer-shared.html; this runs BEFORE stamp-footer
// (see save.bat), so correcting the partial here propagates to every footer page.
//
// An optional third element restricts the passes to one region of the file.
// patch.html is the changelog: its entries are history and must never be
// rewritten, so there only the <footer> block (where the live count lives) is
// stamped - a future "N+ file formats" line in a patch entry stays as written.
const FOOTER_REGION = /<footer\b[\s\S]*?<\/footer>/;
const JOBS = [
  ['index.html', [fmtTypes, fmtFormats, fmtFormatsAngle, bareCount]],
  ['about.html', [fmtTypes, fmtFormats, fmtFormatsAngle, bareCount, browseAll]],
  ['formats.html', [fmtTypes, fmtFormats, fmtFormatsAngle, bareCount]],
  ['patch.html', [fmtFormats, bareCount], FOOTER_REGION],
  ['stats.html', [fmtFormats]],
  ['privacy.html', [fmtFormats]],
  ['atari.html', [fmtFormats]],
  ['tools/partials/footer-shared.html', [fmtFormats]],
  ['manifest.json', [fmtTypes]],
  ['sitemap.xml', [
    [/<lastmod>\d{4}-\d{2}-\d{2}<\/lastmod>/g, `<lastmod>${today}</lastmod>`],
  ]],
];

let changed = 0;
for (const [rel, passes, region] of JOBS) {
  // Every job is a website file (-> web/) except the shared footer partial, which
  // lives under tools/ in the repo root.
  const file = join(rel.startsWith('tools/') ? ROOT : WEB, rel);
  let src;
  try {
    src = readFileSync(file, 'utf8');
  } catch (e) {
    console.warn(`stamp-counts: skipped ${rel} (${e.message})`);
    continue;
  }
  const stamp = (text) => { for (const [re, to] of passes) text = text.replace(re, to); return text; };
  // Function replacer: the region text is file content, so it must not be
  // re-parsed for $& / $' patterns.
  const out = region ? src.replace(region, (m) => stamp(m)) : stamp(src);
  if (out !== src) {
    writeFileSync(file, out);
    changed++;
    console.log(`stamp-counts: updated ${rel}`);
  }
}

console.log(`stamp-counts: format count = ${n}, lastmod = ${today}, files changed = ${changed}`);
