/* Stamp the shared footer block (heading + offline-download section) into every
   main page.
   ============================================================================
   WHY: that block - the "Everything runs in your browser" heading plus the whole
   "Download for offline use" section and its dependency list - is identical on
   every page, so it lived copy-pasted across index/about/patch and was missing
   entirely from stats/privacy (and half-present on formats). One change meant
   editing it in several places, and they had already drifted. This bakes it from
   a single source instead.

   HOW: the canonical block lives in tools/partials/footer-shared.html. Each page
   wraps its footer's shared region in FOOTER:START / FOOTER:END markers; this
   script rewrites only what sits between them. Everything else is left alone -
   crucially the page's own .footer-bottom row (its "<- Main page" return button
   and page-specific links), which stays per-page. So the offline block is
   universal while the bottom row is not.

   RUN: `node tools/stamp-footer.mjs` (save.bat runs it on every commit, before
   `git add`, so the pages can never drift from the partial). Re-runnable and
   idempotent.
   ============================================================================ */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// Pages that carry the full footer. The per-format /formats/<ext> pages are
// deliberately excluded - hundreds of thin SEO pages keep their own minimal
// footer (same "main pages only" scope as the visitor counter).
const PAGES = ['index.html', 'about.html', 'patch.html', 'stats.html', 'privacy.html', 'formats.html'];

// The shared block, exactly as it should sit inside <footer> (2-space indented).
const shared = readFileSync(join(ROOT, 'tools/partials/footer-shared.html'), 'utf8').replace(/\r?\n+$/, '');

const START = '<!-- FOOTER:START - generated by tools/stamp-footer.mjs from tools/partials/footer-shared.html; do not hand-edit between the markers -->';
const END = '<!-- FOOTER:END -->';
// Match the whole marked region (markers included), lazily - so it survives any
// earlier short markers and stays stable on re-runs.
const RE = /<!--\s*FOOTER:START[\s\S]*?FOOTER:END\s*-->/;
const block = `${START}\n${shared}\n  ${END}`;

let changed = 0;
const missing = [];
for (const name of PAGES) {
  const file = join(ROOT, name);
  const html = readFileSync(file, 'utf8');
  if (!RE.test(html)) { missing.push(name); continue; }
  // Function replacer so $-sequences in the block are never interpreted.
  const next = html.replace(RE, () => block);
  if (next !== html) { writeFileSync(file, next); changed++; }
}

if (missing.length) {
  console.warn('stamp-footer: FOOTER markers not found in: ' + missing.join(', ') +
    ' - add <!-- FOOTER:START --> ... <!-- FOOTER:END --> inside the <footer>, above .footer-bottom.');
}
console.log(`stamp-footer: stamped ${changed}/${PAGES.length} page(s) from tools/partials/footer-shared.html`);
