/* Stage the website for the Android app.
 *
 * Capacitor copies `webDir` into the APK on every `cap sync`, so webDir is a
 * staged copy (mobile/www/, gitignored) rather than ../web itself. That keeps
 * the same exclusions as the desktop package (electron-builder.yml):
 *
 *   samples/**    19 MB of gallery example files
 *   **\/*.map      source maps - dev-only, regenerated by every tsc build
 *   sitemap*.xml, robots.txt, llms.txt, _headers - crawler and deploy plumbing
 *
 * formats/** stays in, for the desktop's reason: the /formats hub links
 * straight at those pages, and a hub of dead links is worse than 25 MB.
 *
 * It also builds the bridge. mobile/bridge/anr-bridge.js is the preload
 * equivalent, and it needs the encoder rewrite rules from
 * desktop/ffmpeg-accel.mjs. A document-start script cannot import a module,
 * so this inlines the rules ahead of the bridge into ONE classic script and
 * writes it where the native side reads it:
 *
 *   android/app/src/main/assets/anr-bridge.js   (generated, gitignored)
 *
 * It sits OUTSIDE assets/public/ on purpose: `cap sync` owns public/, and the
 * page has no reason to be able to fetch the bridge.
 *
 * Run: node mobile/tools/stage-web.mjs   (mobile.bat and `npm run sync` do)
 */

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const MOBILE = resolve(HERE, '..');
const ROOT = resolve(MOBILE, '..');
const WEB = join(ROOT, 'web');
const OUT = join(MOBILE, 'www');

function excluded(rel) {
  const r = rel.split(sep).join('/');
  const name = basename(r);
  return r === 'samples' || r.startsWith('samples/')
    || name.endsWith('.map')
    || (!r.includes('/') && (/^sitemap.*\.xml$/.test(name) || name === 'robots.txt' || name === 'llms.txt' || name === '_headers'));
}

if (!existsSync(join(WEB, 'index.html'))) {
  console.error('stage-web: ' + WEB + ' has no index.html - is this the repo root?');
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });
cpSync(WEB, OUT, { recursive: true, filter: (src) => !excluded(relative(WEB, src)) });

// Every staged path, '/'-separated. AnrRouter.java loads this list once, so the
// /about -> about.html decision is a set lookup instead of an AssetManager
// open-and-catch per request.
const listing = [];
let bytes = 0, files = 0;
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p);
    else { bytes += st.size; files++; listing.push(relative(OUT, p).split(sep).join('/')); }
  }
})(OUT);
console.log(`stage-web: ${files} files, ${(bytes / 1048576).toFixed(1)} MB -> ${relative(ROOT, OUT)}`);

// ---- the bridge -------------------------------------------------------------

const ASSETS = join(MOBILE, 'android', 'app', 'src', 'main', 'assets');
if (!existsSync(join(MOBILE, 'android'))) {
  console.log('stage-web: no android/ project yet - run `npx cap add android` in mobile/, then stage again');
  process.exit(0);
}

const accelSrc = readFileSync(join(ROOT, 'desktop', 'ffmpeg-accel.mjs'), 'utf8');
// ffmpeg-accel.mjs is kept inline-able on purpose: no imports, and every export
// is a plain `export const` / `export function`. Refuse anything else rather
// than emit a bridge that dies with a syntax error at document start.
if (/^\s*import\s/m.test(accelSrc) || /^\s*export\s*\{/m.test(accelSrc) || /^\s*export\s+default\b/m.test(accelSrc)) {
  console.error('stage-web: desktop/ffmpeg-accel.mjs must stay import-free with only `export const|function` exports');
  process.exit(1);
}
const exported = [...accelSrc.matchAll(/^export\s+(?:const|function)\s+([A-Za-z_$][\w$]*)/gm)].map((m) => m[1]);
const accelBody = accelSrc.replace(/^export\s+(const|function)\s/gm, '$1 ');

const bridgeSrc = readFileSync(join(MOBILE, 'bridge', 'anr-bridge.js'), 'utf8');
const bundle = [
  '/* GENERATED by mobile/tools/stage-web.mjs - edit mobile/bridge/anr-bridge.js',
  '   and desktop/ffmpeg-accel.mjs, never this file. */',
  '(function () {',
  "'use strict';",
  // A second injection (a WebView that re-runs document-start scripts on an
  // SPA swap it counts as a navigation) must not redefine the bridge.
  'if (window.anrDesktop) return;',
  'const AnrAccel = (function () {',
  accelBody,
  'return { ' + exported.join(', ') + ' };',
  '})();',
  bridgeSrc,
  '})();',
  '',
].join('\n');

mkdirSync(ASSETS, { recursive: true });
writeFileSync(join(ASSETS, 'anr-bridge.js'), bundle);
writeFileSync(join(ASSETS, 'anr-files.txt'), listing.sort().join('\n') + '\n');

// ---- the FFmpeg executable ------------------------------------------------------
//
// mobile/ffmpeg/build-android.sh (or its GitHub workflow) leaves the binary in
// mobile/ffmpeg/out/<abi>/ffmpeg. It ships as jniLibs/<abi>/libanrffmpeg.so -
// an executable with a library's name, because the native library folder is
// the one place Android lets an app execute a file from (AnrFfmpeg.java).
// Absent is fine: the app then runs ffmpeg.wasm, exactly as the website does,
// and a binary copied in by hand earlier is left where it is.
const FF_OUT = join(MOBILE, 'ffmpeg', 'out');
for (const abi of ['arm64-v8a', 'x86_64']) {
  const bin = join(FF_OUT, abi, 'ffmpeg');
  if (!existsSync(bin)) continue;
  const dest = join(MOBILE, 'android', 'app', 'src', 'main', 'jniLibs', abi);
  mkdirSync(dest, { recursive: true });
  cpSync(bin, join(dest, 'libanrffmpeg.so'));
  console.log(`stage-web: ffmpeg (${(statSync(bin).size / 1048576).toFixed(1)} MB) -> ${relative(ROOT, join(dest, 'libanrffmpeg.so'))}`);
}
console.log(`stage-web: bridge (${(bundle.length / 1024).toFixed(1)} KB, rules: ${exported.join(', ')}) -> ${relative(ROOT, join(ASSETS, 'anr-bridge.js'))}`);
